### ISSUE TITLE
Empty 'Categories'

### ISSUE THREAD

**Issue by WanderingFox** [doadin/Baggins#10]
Running baggins v3.1.4 and the latest Ace3 libs.

Bag/Category config screen shows all of the bags just fine, but the Categories display is completely empty (see screenshot). No error message is being generated and all of the bag categories are working just fine. It's just impossible to edit them.

The dropdown to add a new category to a bag *does* see the list of existing categories.

It's happening with no other addons loaded.

![image](https://user-images.githubusercontent.com/2967926/69010283-2dcf6900-092c-11ea-9ddb-7084bd6636f4.png)

![image](https://user-images.githubusercontent.com/2967926/69010318-7e46c680-092c-11ea-8e26-4e249157bde3.png)

**Comment by doadin** [comment]
Yes, am aware of the issue. The code to generate the categories menu works on classic but not retail. The code was removed from running on retail as it not only generated an error but also made the whole  BagginsEdit window not show at all.

**Comment by doadin** [comment]
an at least temp solution has been found and released in v3.1.5 .
