### ISSUE TITLE
Feature request: Rule that executes a search / or rule for expansion

### ISSUE THREAD

**Issue by claytonkimber** [doadin/Baggins#101]
Using "BFA" in search I can get all of the BFA items, which is amazing.  I want to create a category for BFA scrappables, but seems that I would either need rule for that expansion or a rule that would give results from a search.

**Comment by doadin** [comment]
I have added via this commit: 445a75e689cf30fb1d6ea3dca9c5db8764595936 whcih is a part of the update v5.3.0 a filter/rule for scrapable items. Let me know if you have any issue with this. Thanks!
