### ISSUE TITLE
BUG [log]

### ISSUE THREAD

**Issue by claytonkimber** [doadin/Baggins#104]
Log from bugsack error upon logging in

2095x Baggins/Baggins-Search.lua:123: attempt to index a nil value
[string "@Baggins/Baggins-Search.lua"]:123: in function `Search'
[string "@Baggins/Baggins-Search.lua"]:310: in function `handler'
[string "@Baggins/Baggins.lua"]:201: in function `FireSignal'
[string "@Baggins/Baggins.lua"]:774: in function `?'
[string "@Baggins/Baggins.lua"]:175: in function <Baggins/Baggins.lua:167>

Locals:
self = <table> {
 Search = <function> defined @Baggins/Baggins-Search.lua:116
 UpdateEditBoxPosition = <function> defined @Baggins/Baggins-Search.lua:261
}
search = ""
itemName = nil
itemQuality = nil
itemLevel = nil
itemType = nil
itemSubType = nil
itemEquipLoc = nil
bindType = nil
expacID = nil
setID = nil
effectiveILvl = nil
isPreview = nil
baseILvl = nil
GearILevel = nil
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = BagginsBag1 {
 }
 2 = BagginsBag2 {
 }
 3 = BagginsBag3 {
 }
 4 = BagginsBag4 {
 }
 5 = BagginsBag5 {
 }
 6 = BagginsBag6 {
 }
 7 = BagginsBag7 {
 }
 8 = BagginsBag8 {
 }
 9 = BagginsBag9 {
 }
 10 = BagginsBag10 {
 }
 11 = BagginsBag11 {
 }
 12 = BagginsBag12 {
 }
}
(for control) = 1
_ = 1
bag = BagginsBag1 {
 BottomLeftCorner = Texture {
 }
 OnBackdropLoaded = <function> defined @SharedXML/Backdrop.lua:152
 GetBackdropColor = <function> defined @SharedXML/Backdrop.lua:390
 TopLeftCorner = Texture {
 }
 RightEdge = Texture {
 }
 closebutton = BagginsBag1CloseButton {
 }
 ApplyBackdrop = <function> defined @SharedXML/Backdrop.lua:294
 SetBackdrop = <function> defined @SharedXML/Backdrop.lua:329
 ClearBackdrop = <function> defined @SharedXML/Backdrop.lua:282
 GetBackdropBorderColor = <function> defined @SharedXML/Backdrop.lua:409
 title = BagginsBag1Title {
 }
 SetBorderBlendMode = <function> defined @SharedXML/Backdrop.lua:266
 bagid = 1
 sections = <table> {
 }
 PixelSnapDisabled = true
 bagparents = <table> {
 }
 SetupTextureCoordinates = <function> defined @SharedXML/Backdrop.lua:214
 OnBackdropSizeChanged = <function> defined @SharedXML/Backdrop.lua:182
 TopRightCorner = Texture {
 }
 isempty = false
 GetEdgeSize = <function> defined @SharedXML/Backdrop.lua:188
 tfade = Texture {
 }
 Center = Texture {
 }
 TopEdge = Texture {
 }
 0 = <userdata>
 BottomRightCorner = Texture {
 }
 compressbutton = BagginsBag1CompressButton {
 }
 BottomEdge = Texture {
 }
 backdropInfo = <table> {
 }
 HasBackdropInfo = <function> defined @SharedXML/Backdrop.lua:278
 SetBackdropBorderColor = <function> defined @SharedXML/Backdrop.lua:422
 SetupPieceVisuals = <function> defined @SharedXML/Backdrop.lua:246
 SetBackdropColor = <function> defined @SharedXML/Backdrop.lua:399
 LeftEdge = Texture {
 }
 GetBackdrop = <function> defined @SharedXML/Backdrop.lua:347
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = BagginsBag1Section1 {
 }
 2 = BagginsBag1Section2 {
 }
 3 = BagginsBag1Section3 {
 }
 4 = BagginsBag1Section4 {
 }
 5 = BagginsBag1Section5 {
 }
 6 = BagginsBag1Section6 {
 }
}
(for control) = 3
_ = 3
section = BagginsBag1Section3 {
 0 = <userdata>
 bagid = 1
 titleframe = BagginsBag1SectionTitleFrame {
 }
 set_title = "Trash"
 slots = <table> {
 }
 itemcount = 12
 needssorting = true
 secid = 3
 layout = <table> {
 }
 items = <table> {
 }
 title = BagginsBag1SectionTitle {
 }
 used = true
 layout_areaid = 1
 layout_columns = 8
 layout_waste = 773626.000591
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = BagginsPooledItemButton60 {
 }
 2 = BagginsPooledItemButton164 {
 }
 3 = BagginsPooledItemButton107 {
 }
 4 = BagginsPooledItemButton106 {
 }
 5 = BagginsPooledItemButton150 {
 }
 6 = BagginsPooledItemButton181 {
 }
 7 = BagginsPooledItemButton163 {
 }
 8 = BagginsPooledItemButton166 {
 }
 9 = BagginsPooledItemButton162 {
 }
 10 = BagginsPooledItemButton154 {
 }
 11 = BagginsPooledItemButton155 {
 }
 12 = BagginsPooledItemButton192 {
 }
}
(for control) = 12
_ = 12
button = BagginsPooledItemButton192 {
 0 = <userdata>
 OnLeave = <function> defined @FrameXML/ContainerFrame.lua:1493
 SetItem = <function> defined @FrameXML/ItemButtonTemplate.lua:544
 IconOverlay = Texture {
 }
 SetAlpha = <function> defined @FrameXML/ItemButtonTemplate.lua:631
 UpdateCooldown = <function> defined @FrameXML/ContainerFrame.lua:1704
 showMatchHi

**Comment by doadin** [comment]
I noticed from your other issue you seem to be installing from github and not curseforge?

**Comment by claytonkimber** [comment]
Normally install from Curseforge, but for testing the scrap integration I pulled from github.  0.5 was what I pulled and forge is now at .8, so I'm not sure if this is still relevant

**Comment by doadin** [comment]
if this is still an issue please reopen.
