### ISSUE TITLE
Baggins.lua errors - addon unusable for me.

### ISSUE THREAD

**Issue by Rechoque** [doadin/Baggins#105]
**From Bugsack I get this error on load:**

3x Interface_Wrath\FrameXML\Bindings.xml:1 Baggins/Baggins-Search.lua:1 (null)

**When I try to use the addon by opening my bags, there's a recurring error:**

798x Baggins/Baggins.lua:3190: attempt to call field 'IsAddOnLoaded' (a nil value)
[string "@Baggins/Baggins.lua"]:3190: in function `UpdateItemButton'
[string "@Baggins/Baggins.lua"]:1896: in function `ReallyLayoutSection'
[string "@Baggins/Baggins.lua"]:761: in function `?'
[string "@Baggins/Baggins.lua"]:175: in function <Baggins/Baggins.lua:167>

Locals:
self = <table> {
 cannotDetachTooltip = true
 modules = <table> {
 }
 CancelTimer = <function> defined @Ace3/AceTimer-3.0/AceTimer-3.0.lua:147
 CreateItemButton = <function> defined @Baggins/Baggins.lua:2479
 GetIncludeRule = <function> defined @Baggins/Baggins-Filtering.lua:461
 RemoveSection = <function> defined @Baggins/Baggins.lua:3889
 GetCachedItem = <function> defined @Baggins/Baggins-Filtering.lua:533
 OptimizeSectionLayout = <function> defined @Baggins/Baggins.lua:1544
 UpdateSectionContents = <function> defined @Baggins/Baggins.lua:1199
 IsAnyBankOpen = <function> defined @Baggins/Baggins.lua:4165
 RemoveRule = <function> defined @Baggins/Baggins.lua:3906
 OnTextUpdate = <function> defined @Baggins/Baggins.lua:3629
 InitOptions = <function> defined @Baggins/Baggins-Options.lua:1082
 ScheduleTimer = <function> defined @Ace3/AceTimer-3.0/AceTimer-3.0.lua:94
 UpdateDB = <function> defined @Baggins/Baggins-Options.lua:1063
 GetBagTypes = <function> defined @Baggins/Baggins-Filtering.lua:89
 UpdateItemButtons = <function> defined @Baggins/Baggins.lua:2944
 LayoutSection = <function> defined @Baggins/Baggins.lua:1834
 OnBankOpened = <function> defined @Baggins/Baggins.lua:712
 SetEnabledState = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:420
 Hook = <function> defined @Ace3/AceHook-3.0/AceHook-3.0.lua:273
 RegisterSkin = <function> defined @Baggins/Baggins-Skins.lua:34
 InitBagCategoryOptions = <function> defined @Baggins/Baggins-Options.lua:3592
 UpdateLayout = <function> defined @Baggins/Baggins.lua:2933
 CountNormalSlots = <function> defined @Baggins/Baggins.lua:3717
 AddCustomRule = <function> defined @Baggins/Baggins-Filtering.lua:101
 RuleTypeIterator = <function> defined @Baggins/Baggins-Filtering.lua:123
 NewModule = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:231
 MoveBag = <function> defined @Baggins/Baggins.lua:3803
 ForceFullRefresh = <function> defined @Baggins/Baggins-Filtering.lua:429
 DoRecheckCompress = <function> defined @Baggins/Baggins-ItemOps.lua:224
 GetAce3Opts = <function> defined @Baggins/Baggins-Filtering.lua:152
 GetName = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:275
 MoveRule = <function> defined @Baggins/Baggins.lua:3838
 defaultcategories = <table> {
 }
 ClearSectionCaches = <function> defined @Baggins/Baggins.lua:998
 Disable = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:310
 CategoryMatchRemoved = <function> defined @Baggins/Baggins.lua:870
 Unhook = <function> defined @Ace3/AceHook-3.0/AceHook-3.0.lua:417
 CloseSpecialWindows = <function> defined @Baggins/Baggins.lua:4199
 CreateBagPlacementFrame = <function> defined @Baggins/Baggins.lua:1952
 IncludeItemInCategory = <function> defined @Baggins/Baggins-Filtering.lua:493
 Debug = <function> defined @Baggins/Baggins.lua:118
 CategoryMatchAdded = <function> defined @Baggins/Baggins.lua:810
 FireSignal = <function> defined @Baggins/Baggins.lua:198
 IsActive = <function> defined @Baggins/Baggins.lua:393
 CountAmmoSlots = <function> defined @Baggins/Baggins.lua:3721
 SlotMoved = <function> defined @Baggins/Baggins.lua:909
 SetDefaultModuleLibraries = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:363
 Baggins_CategoriesChanged = <function> defined @Baggins/Baggins.lua:513
 CloseBag = <function> defined
 
 
 The addons has become completely unusable for me.

**Comment by Elberet** [comment]
Can confirm, I had to downgrade to version 5.0.8 and comment out lines 3-35 from `Baggins-Search.lua` and lines 27-29 from `src/filters/ScrapAddon.lua`, as all calls to `IsAddOnLoaded` fail - which is strange, since `/run print(IsAddOnLoaded("Baggins"))` works just fine.

I'm playing WoW WotLK Classic.

**Comment by doadin** [comment]
sorry this should be fixed in v5.1.1 .
