### ISSUE TITLE
ItemType rule not working

### ISSUE THREAD

**Issue by Celunari** [doadin/Baggins#108]
When creating custom categories; the rule for Item Type has no select-able information. Not even displaying rules added after Item Type
![WoWScrnShot_050324_093707](https://github.com/doadin/Baggins/assets/168843584/80a63b36-c3d9-4d57-ac8c-ee979f60e0db)

When I change Item Type to any other rule, the rules after will populate.
![WoWScrnShot_050324_093755](https://github.com/doadin/Baggins/assets/168843584/3494452a-67e7-40c4-8062-8923f3edbd9a)

This is on version 5.1.6-cata

**Comment by doadin** [comment]
This issue should be fixed by: cf6139a50abcdb84ac7cead422b49db3f9df0ac5 which is included in v5.1.7
