### ISSUE TITLE
Error - Can't open backpack

### ISSUE THREAD

**Issue by Dakar2008Inropa** [doadin/Baggins#109]
Getting following error when trying to open my backpack

`1x Baggins/Baggins-Filtering.lua:374: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: ?
[string "@Baggins/Baggins-Filtering.lua"]:374: in function `OnSlotChanged'
[string "@Baggins/Baggins-Filtering.lua"]:288: in function `CheckSlotsChanged'
[string "@Baggins/Baggins-Filtering.lua"]:438: in function `ForceFullUpdate'
[string "@Baggins/Baggins.lua"]:4054: in function `OpenBag'
[string "@Baggins/Baggins.lua"]:4093: in function `OpenAllBags'
[string "@Baggins/Baggins.lua"]:4117: in function <Baggins/Baggins.lua:4109>
[string "=(tail call)"]: ?
[string "TOGGLEBACKPACK"]:1: in function <[string "TOGGLEBACKPACK"]:1>

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1
`

**Comment by doadin** [comment]
Is this in retail, classic , cata?

**Comment by Dakar2008Inropa** [comment]
cata

**Comment by Dakar2008Inropa** [comment]
Still can't get baggins to work with Cataclysm Classic, i have tried to disable all other addons so baggins was the only one enabled, and still it fails to show the when pressing bag button:

get this error:

1x Baggins/Baggins-Filtering.lua:374: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: ?
[string "@Baggins/Baggins-Filtering.lua"]:374: in function `OnSlotChanged'
[string "@Baggins/Baggins-Filtering.lua"]:288: in function `CheckSlotsChanged'
[string "@Baggins/Baggins-Filtering.lua"]:438: in function `ForceFullUpdate'
[string "@Baggins/Baggins.lua"]:4054: in function `OpenBag'
[string "@Baggins/Baggins.lua"]:4093: in function `OpenAllBags'
[string "@Baggins/Baggins.lua"]:4117: in function <Baggins/Baggins.lua:4109>
[string "=(tail call)"]: ?
[string "TOGGLEBACKPACK"]:1: in function <[string "TOGGLEBACKPACK"]:1>

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

**Comment by doadin** [comment]
Have you tried deleteing the SavedVariables file for Baggins? Should be located in (World of Warcraft\_classic_\WTF\Account\*YOURACCOUNTNAME*\SavedVariables\Baggins.lua ) or tried resetting profile in game by right-clicking the minimap icon, then then choosing config window > Profile > Reset Profile? This issue was fixed back in https://github.com/doadin/Baggins/commit/a677b361e02e82d40f61ca073665ec4eaad9cf5c and just to make sure, I deleted my savedvariables then loaded into the game and its working just fine.

**Comment by doadin** [comment]
I just pushed another update that just in case maybe you had baggins before cata support was added or something and maybe something got setup wrong the new update should make this error in particular impossible and it should correct this issue. v5.2.0 has this change in it https://github.com/doadin/Baggins/commit/49b0c0031552ba77a2c9d6d070acf5da63772fdd.
