### ISSUE TITLE
Equipped items incorrectly appearing in bags

### ISSUE THREAD

**Issue by Jordan466** [doadin/Baggins#111]
The last maintenance has somehow introduced an issue where my equipped items are now appearing in my bag when they shouldn't appear at all. 

In these screenshots, all of these items are equipped, and not actually in my bag. Mousing over them provides no tooltip

![image](https://github.com/doadin/Baggins/assets/24884680/b333d95d-521e-4430-8689-aeb77404173d)
![image](https://github.com/doadin/Baggins/assets/24884680/56a1a921-4cfb-4251-a6d5-865e17118e26)
![image](https://github.com/doadin/Baggins/assets/24884680/669093cf-7e1d-47a2-b468-4ecf357da621)
![image](https://github.com/doadin/Baggins/assets/24884680/c7a39203-8976-4574-97a3-97de403fcf42)

I'm playing Classic cata if it makes a difference

**Comment by doadin** [comment]
classing this as same issue as #112
