### ISSUE TITLE
Radio buttons in minimap popup-menu are broken

### ISSUE THREAD

**Issue by Elberet** [doadin/Baggins#114]
The radio buttons for "Hide Default Bank" and "Override Default Bags" in the minimap popup-menu do not reflect the actual state of the toggled options. For example, the menu might show `bank = on` and `bags = off`, but Baggins and the default UI will behave as tho the option where enabled.

Game version: Wow Cataclysm Classic, english locale.
Baggins version(s): 5.3.3 - 5.3.5, possibly since 2b9a1ff645e092cc2675a81429e8e1ceb7bda16c

**Comment by Elberet** [comment]
Looks like the indices referenced in `updateMenu()` are wrong. The change added a new menu entry, shifting the two menu items down by one (or up one in array index):

https://github.com/doadin/Baggins/blob/2b9a1ff645e092cc2675a81429e8e1ceb7bda16c/Baggins.lua#L274-L275

**Comment by doadin** [comment]
This commit( 558694b671b2f86b53cc573387c38088ed52b88a ) included in v5.3.6, should address this issue, let me know if you still have issues. Thanks!
