### ISSUE TITLE
Only first visible baggins bag is populated on entering game

### ISSUE THREAD

**Issue by Elberet** [doadin/Baggins#115]
Immediately after entering the game or reloading the UI, only the first (in bag/category config order) visible (i.e. the bag has "Open With All" enabled) baggins bag is populated with item buttons; all other bags are empty, showing empty window frames without either category headers or items.

After visiting the bank, all baggins bags - both bank and backpack - are updated and show their contents.

Game version: Wow Cataclysm Classic, english locale.
Baggins version(s): 5.3.5

**Comment by doadin** [comment]
This commit ( 2d54c070ea8f428d66c65748763809a6cb4b007b ) included in v5.3.6, should address this issue, please let me know if you still have issues after updating. Thanks!

**Comment by doadin** [comment]
more on this being tracked here: https://github.com/doadin/Baggins/issues/116
