### ISSUE TITLE
Error With Caged Pet In Bags

### ISSUE THREAD

**Issue by IrishMoxie** [doadin/Baggins#12]
I'm using version 3.2.0 on retail, and receive the following error on the character that has pets in her bag.

436x Baggins\Baggins-v3.2.0.lua:1311: Usage: GetPetInfoBySpeciesID(speciesID)
[string "=[C]"]: in function `GetPetInfoBySpeciesID'
[string "@Baggins\Baggins-v3.2.0.lua"]:1311: in function <Baggins\Baggins.lua:1306>
[string "@Baggins\Baggins-v3.2.0.lua"]:1323: in function <Baggins\Baggins.lua:1319>
[string "=[C]"]: ?
[string "@Baggins\Baggins-v3.2.0.lua"]:1437: in function `SortItemList'
[string "@Baggins\Baggins-v3.2.0.lua"]:1233: in function `UpdateSectionContents'
[string "@Baggins\Baggins-v3.2.0.lua"]:1149: in function `UpdateSection'
[string "@Baggins\Baggins-v3.2.0.lua"]:1123: in function `ReallyUpdateBags'
[string "@Baggins\Baggins-v3.2.0.lua"]:771: in function `?'
[string "@Baggins\Baggins-v3.2.0.lua"]:133: in function <Baggins\Baggins.lua:125>

Locals:
(*temporary) = nil

**Comment by doadin** [comment]
should be fixed in v3.2.1. Thanks!
