### ISSUE TITLE
Tooltip text filter no longer works

### ISSUE THREAD

**Issue by Elberet** [doadin/Baggins#120]
The tooltip item filter appears to no longer work in Cataclysm Classic.

I have a category for items contained in an equipment set using a single tooltip filter looking for the text `"Equipment Sets:"` (obviously, this is locale dependent). None of my items that are in any equipment set are being filtered by this category. Changing the filter to another type of filter, e.g. item name, works as expected, so the bag and category setup is working as intended. Changing the filter string to e.g. `"Unique"` also has no effect.

Since each change of the filter string triggered #118, I had to do a `/reload` after each change during testing.
Also, I'm using a tooltip filter instead of the equipment set filter because of #119.

This was observed on Cataclysm Classic with Baggins 5.4.1 with the english language client.
Last known good Baggins version is 5.3.3.

**Comment by Elberet** [comment]
Well, this is awkward. After playing for a bit and switching between characters, the filter works again. I have no idea what exactly changed; likely, actually switching characters triggers different events than simply `/reload`ing the UI?

Then again, parts of the issue remain. Changing the filter's configuration (i.e. filter string) triggers the LUA error and has no effect until, presumably, logging the character out and back in.

**Comment by doadin** [comment]
If you could please let me know if this persists after updating to v5.4.2, I wonder if the error was causing issues , thanks!

**Comment by doadin** [comment]
I have noticed the bags will not change layout when the category is changed, im looking into this.

**Comment by Elberet** [comment]
The layout not being updated isn't limited to when a category is changed, it also happens when I equip or otherwise remove an item from my inventory. The layout stays fixed, even when using the "Reset New Items" command from the popup menu.

**Comment by doadin** [comment]
I beleieve tooltip now works in latest build, reopen if not. Thanks!
