### ISSUE TITLE
Item compression Temporarily disabling item stack compression no longer works

### ISSUE THREAD

**Issue by Elberet** [doadin/Baggins#121]
My character currently has two stacks of 20 and 1 Shiny Fish Scales in their inventory. Baggins is configured to compress soul shards, stackable items and empty slots and, as expected, shows one stack of 21 items. Enabling the "Disable Compression Temporarily" option from the bag popup menu, however, does not actually disable compression; even after clicking the menu option, I only see one 21 item stack instead of the two stacks that are actually in the character's inventory.

This happened on Cataclysm Classic with the english language client and Baggins 5.4.1.

**Comment by doadin** [comment]
does normal compress/not compressed work?

**Comment by Elberet** [comment]
Nope, toggling "Compress Stackable Items" in the main Baggins options has no effect. Could this be related to the problem that the layout isn't being updated that you've noticed in the other issue?

**Comment by Elberet** [comment]
FYI: disabling compression *technically* works in v5.4.6, but with the same caveat that the Baggins bags aren't being refreshed, so the effect of the option isn't visible. Forcing the refresh by moving any item from any slot to any other slot shows - i.e. triggering a `BAG_UPDATE` game event - correctly updates Baggins, including the (temporarily) changed compression.
