### ISSUE TITLE
In Use category doesn't show until I switch gear sets in Equipment Manager 

### ISSUE THREAD

**Issue by StrykerJC** [doadin/Baggins#122]
When I log into a character that has multiple gear sets in Equipment Manager, I cannot see the "In Use" category of items right away for items that are from other gear sets/specifications.  When I switch gear sets in Equipment Manager, the items for the other specification show up in the "In Use" category as expected.  As long as I remain logged in, the proper behavior persists.  When I log out and back in on the same character, the "in Use" category disappears again until I switch gear sets.

I'm using 5.4.5, but have witnessed this behavior on multiple newer versions of Baggins.  5.3.5 is the last version I have used where this issue doesn't seem to exist.

**Comment by StrykerJC** [comment]
Correction, it's 5.3.3 that is the last version that this issue doesn't exist.

I also noticed that the lag when accessing the bank is back with 5.4.5.  

I've reverted to 5.3.3 for the time being.  This seems to be the last version that works for me without issues.

**Comment by doadin** [comment]
closeing this and other issues that are similar to track in one place: https://github.com/doadin/Baggins/issues/124
