### ISSUE TITLE
Warband items are getting doubled into inventory when the warband bank is open

### ISSUE THREAD

**Issue by WanderingFox** [doadin/Baggins#130]
Note the memory of kalimdor (orange motes with a stack of 3 and a stack of 2). Only the stack of 2 is in my inventory, and only the stack of 3 is in my warband bank, yet baggins shows both of them in my inventory. It doesn't have this behavior with the regular bank or guild bank.

![image](https://github.com/user-attachments/assets/cfa2c77b-6552-4f71-9f67-59c3aa7d56fc)

**Comment by doadin** [comment]
Fixed : e8de6070b6acd005d5b17d2ac1510cf8803c80c1 included in v5.5.3 .
