### ISSUE TITLE
A couple of swatted bugs

### ISSUE THREAD

**Issue by StrykerJC** [doadin/Baggins#136]
For the most part, this addon is working great and is a huge QoL tool for me.  I am, however, seeing occasional BugSwatter issues from it.  It seems to trigger most when I am messing with the guild roster.  Here are the BugSwatter outputs:

1x [ADDON_ACTION_FORBIDDEN] AddOn 'Baggins' tried to call the protected function 'SetGuildRankOrder()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `SetGuildRankOrder'
[string "@Blizzard_Communities/GuildRoster.lua"]:40: in function <Blizzard_Communities/GuildRoster.lua:38>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@Blizzard_Menu/Menu.lua"]:872: in function `Pick'
[string "@Blizzard_Menu/MenuTemplates.lua"]:74: in function <Blizzard_Menu/MenuTemplates.lua:68>

Locals:
Skipped (In Encounter)

--

1x [ADDON_ACTION_FORBIDDEN] AddOn 'Baggins' tried to call the protected function 'SetNote()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `SetNote'
[string "@Blizzard_StaticPopup_Frame/Mainline/StaticPopup.lua"]:2741: in function `EditBoxOnEnterPressed'
[string "@Blizzard_StaticPopup/StaticPopup.lua"]:885: in function `StaticPopup_EditBoxOnEnterPressed'
[string "*StaticPopup.xml:150_OnEnterPressed"]:1: in function <[string "*StaticPopup.xml:150_OnEnterPressed"]:1>

Locals:
_ = Frame {
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
}

**Comment by doadin** [comment]
This must be due to addon taint, as no where in Baggins is either of the mentioned functions called.
