### ISSUE TITLE
Classic: Bag free space calculation is wrong

### ISSUE THREAD

**Issue by SterlingNerd** [doadin/Baggins#19]
LibBagUtils is still using the bitmask for bag types, so it's including keyring free space in general free space calculations.

![image](https://user-images.githubusercontent.com/20735173/74514259-0bb09d00-4ec1-11ea-8ea2-01c0bb05e53e.png)

**Comment by SterlingNerd** [comment]
I haven't made a pull request for this one because it's kinda a mess. However, it seems to be working for me.

https://github.com/SterlingNerd/Baggins/commit/c2be17b95dd7571394e3fa73b432a6e2caf07664

I don't have fubar, so i haven't tested that part but something like that should work...

**Comment by Willy130683** [comment]
Can this please be integrated. To me this is the biggest issue right now ;)

**Comment by SterlingNerd** [comment]
It looks like they're working on it. Until then, here's the hacked up version i've been using with classic: https://github.com/SterlingNerd/Baggins/releases/tag/v3.2.4-classicfix

**Comment by doadin** [comment]
I have added in https://github.com/SterlingNerd/Baggins/commit/c2be17b95dd7571394e3fa73b432a6e2caf07664 about to release it.

**Comment by doadin** [comment]
Look for v3.3.5.

**Comment by Willy130683** [comment]
nice, thanks for the work!
