### ISSUE TITLE
categories bugged.

### ISSUE THREAD

**Issue by pappabjoern** [doadin/Baggins#20]
Hi,
Everytime I click on a category I get the below error.
I've tried reinstall everything, and disabled every other addon that I have but I get the same error all the time.

Message: Interface\AddOns\Baggins\Baggins-Filtering.lua:733: attempt to call upvalue 'GetAuctionItemSubClasses' (a nil value)
Time: Sat Feb 15 19:24:33 2020
Count: 1
Stack: Interface\AddOns\Baggins\Baggins-Filtering.lua:733: attempt to call upvalue 'GetAuctionItemSubClasses' (a nil value)
[string "@Interface\AddOns\Baggins\Baggins-Filtering.lua"]:733: in function `member'
[string "@Interface\AddOns\Baggins\Libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:221: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:169>
[string "@Interface\AddOns\Baggins\Libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:1235: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1117>
[string "@Interface\AddOns\Baggins\Libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:1144: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1117>
[string "@Interface\AddOns\Baggins\Libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:1648: in function `FeedGroup'
[string "@Interface\AddOns\Baggins\Libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:1573: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1557>
[string "=[C]"]: ?
[string "@Interface\AddOns\Baggins\Libs\AceGUI-3.0\AceGUI-3.0.lua"]:72: in function <...erface\AddOns\Baggins\Libs\AceGUI-3.0\AceGUI-3.0.lua:70>
[string "@Interface\AddOns\Baggins\Libs\AceGUI-3.0\AceGUI-3.0.lua"]:290: in function `Fire'
[string "@Interface\AddOns\Baggins\Libs\AceGUI-3.0\widgets\AceGUIContainer-TreeGroup.lua"]:529: in function `Select'
[string "@Interface\AddOns\Baggins\Libs\AceGUI-3.0\widgets\AceGUIContainer-TreeGroup.lua"]:537: in function `SelectByValue'
[string "@Interface\AddOns\Baggins\Libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:1744: in function `FeedGroup'
[string "@Interface\AddOns\Baggins\Libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:1928: in function `Open'
[string "@Interface\AddOns\Baggins\Baggins-Options.lua"]:2048: in function `OpenEditConfig'
[string "@Interface\AddOns\Baggins\Baggins.lua"]:222: in function `func'
[string "@Interface\FrameXML\UIDropDownMenu.lua"]:889: in function `UIDropDownMenuButton_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Locals: <none>

**Comment by doadin** [comment]
Fixed, https://github.com/doadin/Baggins/commit/adc2cb437e55c022c754564722f05a824b81da0a .
Look for v3.2.7 .
