### ISSUE TITLE
BUG:  Preset 'allinonesorted' generates error.

### ISSUE THREAD

**Issue by thohell** [doadin/Baggins#22]
I can recreate this reliably on Retail as such;

1. Open Config Window -> Presets
2. Select 'default' and click 'Reset Profile'
3. Config Window -> Profile
4. Click 'Reset Profile'
5. Open ALL bags (the bug doesn't appear with none or only one bag open).
6. Open Config Window -> Presets
7. Select 'allinonesorted' and click 'Reset Profile'

![bild](https://user-images.githubusercontent.com/6845128/81008770-c5316580-8e53-11ea-8460-8308ccd456a6.png)

**Comment by doadin** [comment]
fixed by closing all open bags before reset.
