### ISSUE TITLE
Q: Baggins:GetRuleDesc() dead code?

### ISSUE THREAD

**Issue by thohell** [doadin/Baggins#24]
`function Baggins:GetRuleDesc(rule)` seems to be dead code. It is never used anywhere from within Baggins.

Is it ever used from other addons? If not, that it should be factored out from `Baggins-filtering.lua`and all associated filter rules.

**Comment by doadin** [comment]
Have not confirmed its use within baggins but of the four baggins plugings still showing up in curse/wowinterface it is never used. I think its safe to remove.

**Comment by thohell** [comment]
We could start with asserting a popup message in the function urging the
user to report back to you. That way we take out the guesswork, and don't
have to chance. By tagging the code in the cleanup, it will be a breeze to
bulk remove everything at a later date.

Den tis 5 maj 2020 21:33doadin <notifications@github.com> skrev:
