### ISSUE TITLE
BUG: ContainerType filter needs a full refresh after moving bags

### ISSUE THREAD

**Issue by thohell** [doadin/Baggins#25]
ContainerType does not react to container changes.

Needs to execute `Baggins:ForceFullRefresh()` when bags are changed.

Steps to reproduce (One of many ways):
1. Put Herb bag in bag bar
2. Create filter 'Container Type' -> 'Herb Bag'
![bild](https://user-images.githubusercontent.com/6845128/81093118-e9e41680-8f01-11ea-8059-3dc791b2ca40.png)
3. Remove Herb bag from bar
![bild](https://user-images.githubusercontent.com/6845128/81093174-fff1d700-8f01-11ea-8b13-988cd68e1130.png)

**Comment by doadin** [comment]
I just woke up, going through all the changes now, thanks! Not 100% but i think what we are looking for here is RegisterEvent("BAG_CLOSED", Baggins:ForceFullRefresh())

**Comment by thohell** [comment]
Yes, somewhere along those lines. Still a bit unsure where in the code base
it belongs, since more than one filter may benefit from a fix.

Seing as this is a very minor bug, and as far as I can tell not intruduced
by me, I figure it will sort itself out once refactoring is done, and it
should then should be an easy fix.

Den tis 5 maj 2020 21:24doadin <notifications@github.com> skrev:
