### ISSUE TITLE
BUG: Problem with PTSet submenus

### ISSUE THREAD

**Issue by thohell** [doadin/Baggins#26]
Compound submenus (ie. A-P, X-Y etc...) in the PeriodicTableSet filter does not work.

Steps to reproduce:
1. Create category
2. Add rule type "PeriodicTable Set"
3. Click Edit
4. Open InstanceLoot (for example)
5. Try to open any of the submenus

![bild](https://user-images.githubusercontent.com/6845128/81113554-b795e180-8f20-11ea-8680-45eed86a19a8.png)

**Comment by doadin** [comment]
This sems to be only an issue with GearSet, InstanceLoot, and InstanceLootHeroic. Other menus go even further into sub levels.

**Comment by thohell** [comment]
Yes, correct.

Den tis 5 maj 2020 kl 23:50 skrev doadin <notifications@github.com>:

**Comment by doadin** [comment]
I believe this to be an upstream issue. The curseforge page says Updated Feb 26, 2020. Latest file has a date of Sep 19, 2018. Not sure what to do about this.

**Comment by thohell** [comment]
Just took a quick look. Pretty sure the bug has something to do with this snippet from Baggins-Filtering.lua. It seems like the submenus A-Z etc. are created by Baggins (possibly to avoid *VERY* long menus för big categories?)

I will take a look at this when i refactor out the filter to PTSet.lua. 

![bild](https://user-images.githubusercontent.com/6845128/81124935-03ec1c00-8f37-11ea-995b-1a69358c4755.png)

**Comment by thohell** [comment]
...on second thought - if the library is very old, maybe the filter should be disabled instead? The data must be ancient. Will check it out.

**Comment by thohell** [comment]
SVN (https://repos.curseforge.com/wow/libperiodictable-3-1/trunk/libperiodictable-3-1) contains data up to and including Lich King.

I guess the only reasonable solution is to disable the filter until someone publishes a newer data-set to use...

**Comment by doadin** [comment]
yea thats kind of what i was thinking it needs an update so its not really that useful at least not the instance ones?

**Comment by thohell** [comment]
I'm tagging the code for removal. The PT3 code is a mess. I will make a PR with 2 commits. The first commit with everything tagged, and the second commit with everything removed.

**Comment by doadin** [comment]
Sounds good, thanks!

**Comment by thohell** [comment]
Should we want to use PT3 for classic, I would much rather rewrite the code into a separate filter. The code was littered across the addon, so it would have been a nightmare to maintain in any case.

I will look into creating a new filter (using the same outdated library, but for classic I guess it wouldnt matter that much). I could probably write the filter so existing rules will work as expected.

**Comment by doadin** [comment]
naw just remove at least for now. I wouldn't bother.
