### ISSUE TITLE
[Bug] Cloth categorized as other

### ISSUE THREAD

**Issue by doadin** [doadin/Baggins#35]
There seems to be a error with the cloth category at least with classic, cloth such as silk cloth show as "other". Changing category > Cloth > Item Subtype to Trade Goods instead of blank seems work fine.

@thohell tagging you in case of any other instances like this I might have missed.

**Comment by thohell** [comment]
I'll take a look at this next week. Full time daddy this week :D

**Comment by doadin** [comment]
Possibly related https://github.com/doadin/Baggins/blob/master/Baggins-Options.lua#L1173
also
https://github.com/doadin/Baggins/pull/37/files#diff-e624a9d636de7c6f62af15683a9cba19R34
There may also be more points of interset idk, as you know the code could sue quite a bit of cleaning.

**Comment by doadin** [comment]
cloth isn't a subtype on classic. removed that default category since it doesn't make sense along with leather.
