### ISSUE TITLE
[Feature request] Search feature

### ISSUE THREAD

**Issue by ctrpetersen** [doadin/Baggins#39]
A search feature would be fantastic, it can get hard to find some items. I don't know how hard it is to implement, but a basic search with graying out of items not matching the search term would be nice.

**Comment by ctrpetersen** [comment]
https://www.curseforge.com/wow/addons/baggins_search

Can confirm this addon still works if you follow the top comment and update L1 of the .toc.

![image](https://user-images.githubusercontent.com/43037308/88289137-1172a000-ccf5-11ea-9af5-c116cd5cbd30.png)

**Comment by doadin** [comment]
Search Added!
