### ISSUE TITLE
Classic issue

### ISSUE THREAD

**Issue by doadin** [doadin/Baggins#4]
Normal Bags open instead of baggins frames when hitting "b" .

**Comment by wolfcon** [comment]
The functions is fine. What do you mean?

Default bag open when click bag (except original one) ?

**Comment by doadin** [comment]
In classic hitting b which just opens the backpack only the blizzard UI for backpack opens, Hitting shift+b baggins opens. On retail just b opens baggins, probably just a difference in keybinds.

**Comment by wolfcon** [comment]
oh. I see. It is definitely keybinding things.
