### ISSUE TITLE
[Feature request] Item quality filter missing options

### ISSUE THREAD

**Issue by Syrions** [doadin/Baggins#41]
Hello,

I want to use a filter with Quality Item, but it's impossible to filter only on objects with quality < Common. There's only "<=" for comparision option available and there's no "Poor" filter in Quality list.

And selecting no Quality don't work either.

![image](https://user-images.githubusercontent.com/50589313/96137300-cb486980-0efc-11eb-9cb3-ac574fae8275.png)
![image](https://user-images.githubusercontent.com/50589313/96137348-d69b9500-0efc-11eb-8ad2-04980a1e5778.png)

Thank your for this addon, he's amazing !

**Comment by doadin** [comment]
Fixed: https://github.com/doadin/Baggins/commit/005667881369f4012c821e1c3f03b5b8e2581ac5

**Comment by Syrions** [comment]
Thanks a lot :) You were really fast ! Good job !
