### ISSUE TITLE
LUA Error

### ISSUE THREAD

**Issue by derekengel** [doadin/Baggins#42]
I just got this error:

Message: ...face\AddOns\Baggins\Libs\LibQTip-1.0\LibQTip-1.0.lua:543: attempt to call method 'GetBackdrop' (a nil value)
Time: Fri Oct 16 13:51:28 2020
Count: 2
Stack: ...face\AddOns\Baggins\Libs\LibQTip-1.0\LibQTip-1.0.lua:543: attempt to call method 'GetBackdrop' (a nil value)
[string "=[C]"]: in function `GetBackdrop'
[string "@Interface\AddOns\Baggins\Libs\LibQTip-1.0\LibQTip-1.0.lua"]:543: in function <...face\AddOns\Baggins\Libs\LibQTip-1.0\LibQTip-1.0.lua:539>
[string "@Interface\AddOns\Baggins\Libs\LibQTip-1.0\LibQTip-1.0.lua"]:132: in function `Acquire'
[string "@Interface\AddOns\Baggins\Baggins.lua"]:230: in function `OnEnter'
[string "@Interface\AddOns\Baggins\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua"]:77: in function <...\AddOns\Baggins\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:60>

Locals:

**Comment by doadin** [comment]
Was this on retail or classic?

**Comment by doadin** [comment]
I think this is related to an issue with LibQTip and it not being updated on curseforge\have a release for 9.0 yet.

**Comment by derekengel** [comment]
Sorry, it was on retail.

**Comment by doadin** [comment]
Hopfully LibQTip wills ee an update soon i'll leave this open till then.

**Comment by doadin** [comment]
LibQTip just released an update hopefully this error will be fixed Baggins v3.6.1 uses the updated LibQTip so look for that.
