### ISSUE TITLE
Baggins no longer opens / LUA Error

### ISSUE THREAD

**Issue by Ruffz** [doadin/Baggins#43]
Hi,

LUA Errors with 3.5.9 (since 3.5.7) on Retail and Beta :

> 26x Baggins\src\filters\ItemLevel.lua:25: attempt to index global 'LIUI' (a nil value)
> [string "@Baggins\src\filters\ItemLevel.lua"]:25: in function `Matches'
> [string "@Baggins\Baggins-Filtering.lua"]:317: in function <Baggins\Baggins-Filtering.lua:288>
> [string "@Baggins\Baggins-Filtering.lua"]:307: in function <Baggins\Baggins-Filtering.lua:288>
> [string "@Baggins\Baggins-Filtering.lua"]:367: in function `OnSlotChanged'
> [string "@Baggins\Baggins-Filtering.lua"]:278: in function `CheckSlotsChanged'
> [string "@Baggins\Baggins-Filtering.lua"]:428: in function `ForceFullUpdate'
> [string "@Baggins\Baggins-Filtering.lua"]:422: in function `ForceFullRefresh'
> [string "@Baggins\Baggins-Options.lua"]:1668: in function `OnProfileEnable'
> [string "@Baggins\Baggins-v3.5.7.lua"]:726: in function <Baggins\Baggins.lua:662>
> [string "=[C]"]: ?
> [string "@ActionBarProfiles\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <...ActionBarProfiles\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
> [string "@ActionBarProfiles\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
> [string "@ActionBarProfiles\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:630: in function <...ActionBarProfiles\libs\AceAddon-3.0\AceAddon-3.0.lua:615>

Thanks for reading.

**Comment by doadin** [comment]
Fixed: https://github.com/doadin/Baggins/commit/ca88e7610761c6e37dca94627f6daaad6b3a8d97
