### ISSUE TITLE
NOT filter broken in classic wow

### ISSUE THREAD

**Issue by JaredR26** [doadin/Baggins#44]
Hi, starting with version 3.5.6-classic, the NOT filters no longer work for categories.  I saw in the notes something that may have been talking about fixing it?  But the latest versions 3.6.0 and 3.6.1 don't work with NOT category filters.

Thanks, love this addon!

**Comment by doadin** [comment]
Sorry what do you mean by "NOT" filter?

**Comment by JaredR26** [comment]
https://i.imgur.com/fHLuvGz.png

Any of the "NOT" items are not excluded from that category starting with version 3.5.6.  Downgrading to 3.5.5 fixes the issue.  I've been using that same filter unchanged for months.

**Comment by JaredR26** [comment]
Restating this a little bit better, I use "set" categories that I manually assign items to, and then I use catch-all categories that are supposed to show any items not in one of my other filters/sets.  Version 3.5.6 stopped the "don't show in catch-all-category" behavior, so all of my items would be showing up in every place.  Hope that explains the issue a little better.

**Comment by doadin** [comment]
Is the issue only for item type or all or is itemtype all that you have noticed? thanks for the info btw.

**Comment by doadin** [comment]
so I tried using a rule with not and it worked. I think this issue is a problem with filtering by category. in my testing i made a rule similar to what you have in that screen shot.
1. Item Type Armor All
2. Not item type armor mail
with this setup I can add and remove the not and the bag updates to add/remove a mail peice.

**Comment by doadin** [comment]
released a new version left me know if the issue still occurs.

**Comment by JaredR26** [comment]
Many thanks, I will test it out when the servers come back up.

**Comment by JaredR26** [comment]
All fixed!  Thank you so much! :D  I've used Baggins since vanilla wow, best bag addon ever.
