### ISSUE TITLE
[OT] GridStatusRaidDebuffs

### ISSUE THREAD

**Issue by SanUI** [doadin/Baggins#45]
Hey, sorry for hijacking this issue tracker, but I have no idea what to try otherwise. Did you ask about GridStatusRaidDebuffs recently? I don't have an account at curseforge anymore, so I have no way to answer you... other than this ;) If it was indeed you, maybe we could use this issue to talk about what you want. If not, please just close it and sorry for the noise.

**Comment by doadin** [comment]
If you mean did i send a message to the authors of https://www.wowace.com/projects/grid-status-raid-debuff yes.

**Comment by SanUI** [comment]
Yeah ok, seems I became _ForgeUser4754337 at some point in the past. I did not touch any code of this since 2010, and what you can download there is just a dummy addon pointing to http://www.curse.com/addons/wow/gridstatusraiddebuff-mop, which also doesn't exist anymore afaikt. That said, if you find any code for that which I have copyright over, I'd gladly place it in the public domain.

**Comment by doadin** [comment]
I have been working with bstassart, and the addon is now at https://www.curseforge.com/wow/addons/plexusstatusraiddebuff . I think we need the other owner/authors to say the same. Which you are the only one to respond so far.

**Comment by SanUI** [comment]
Nice :) Yeah, it was a tad work to hunt you down. The move to twich seems to have disabled accounts at curse, and while I have gotten the notification email, there doesn't seem to be an account associated with it anymore, so I can't login and respond or something... quite messy!

**Comment by doadin** [comment]
The other users have not logged into curseforge to make a user since back when it transitioned to curseforge couple years ago? So honestly wasn't expecting any response. If you know any of the others if you can contact them that would be appreciated.

**Comment by SanUI** [comment]
Uhh no idea how that transfer thing worked out (did I ever log into curseforge? No idea, what was it before? Just curse?), and I can't remember anything even concerning myself (frankly, I remember using Grid and mucking in code a bit, but if it wasn't for your email I'd not have guessed I had anything to do with GridStatusRaidDebuffs), so sorry, I won't be of any help contacting people.

**Comment by doadin** [comment]
np and yea it has switched a couple times and now curseforge was bought by overwolf lol.

**Comment by doadin** [comment]
im going to close this for now. if I get a responce from the others i'll let you know.
