### ISSUE TITLE
TBC Beta addon dead

### ISSUE THREAD

**Issue by nwardoh** [doadin/Baggins#46]
Message: ...Ons\Baggins\Libs\LibBagUtils-1.0\LibBagUtils-1.0.lua:283: table index is nil
Time: Tue Apr 13 07:33:45 2021
Count: 1
Stack: ...Ons\Baggins\Libs\LibBagUtils-1.0\LibBagUtils-1.0.lua:283: table index is nil
[string "@Interface\AddOns\Baggins\Libs\LibBagUtils-1.0\LibBagUtils-1.0.lua"]:283: in main chunk

Locals: MAJOR = "LibBagUtils-1.0"
MINOR = 40
lib = <table> {
 GetContainerNumFreeSlots = <function> defined @Interface\AddOns\Baggins\Libs\LibBagUtils-1.0\LibBagUtils-1.0.lua:198
 GetContainerFamily = <function> defined @Interface\AddOns\Baggins\Libs\LibBagUtils-1.0\LibBagUtils-1.0.lua:178
 MakeLinkComparator = <function> defined @Interface\AddOns\Baggins\Libs\LibBagUtils-1.0\LibBagUtils-1.0.lua:224
 slotLocks = <table> {
 }
}
strmatch = <function> defined =[C]:-1
gsub = <function> defined =[C]:-1
floor = <function> defined =[C]:-1
tconcat = <function> defined =[C]:-1
band = <function> defined =[C]:-1
pairs = <function> defined =[C]:-1
select = <function> defined =[C]:-1
type = <function> defined =[C]:-1
next = <function> defined =[C]:-1
tonumber = <function> defined =[C]:-1
tostring = <function> defined =[C]:-1
GetTime = <function> defined =[C]:-1
IsClassicWow = <function> defined @Interface\AddOns\Baggins\Libs\LibBagUtils-1.0\LibBagUtils-1.0.lua:33
GetContainerNumSlots = <function> defined =[C]:-1
GetContainerNumFreeSlots = <function> defined =[C]:-1
GetContainerItemLink = <function> defined =[C]:-1
GetContainerItemInfo = <function> defined =[C]:-1
GetItemInfo = <function> defined =[C]:-1
GetItemFamily = <function> defined =[C]:-1
BANK_CONTAINER = -1
KEYRING_CONTAINER = nil
NUM_BANKBAGSLOTS = 7
NUM_BAG_SLOTS = 4
REAGENTBANK_CONTAINER = nil
t = <table> {
}
print = <function> defined @Interface\AddOns\Baggins\Libs\LibBagUtils-1.0\LibBagUtils-1.0.lua:63
escapePatterns = <function> defined @Interface\AddOns\Baggins\Libs\LibBagUtils-1.0\LibBagUtils-1.0.lua:77
floor = <function> defined =[C]:-1
compareFuzzySuffix = <function> defined @Interface\AddOns\Baggins\Libs\LibBagUtils-1.0\LibBagUtils-1.0.lua:88
makeLinkComparator = <function> defined @Interface\AddOns\Baggins\Libs\LibBagUtils-1.0\LibBagUtils-1.0.lua:96
GetTime = <function> defined =[C]:-1
lockSlot = <function> defined @Interface\AddOns\Baggins\Libs\LibBagUtils-1.0\LibBagUtils-1.0.lua:147
isLocked = <function> defined @Interface\AddOns\Baggins\Libs\LibBagUtils-1.0\LibBagUtils-1.0.lua:155
GetContainerFamily = <function> defined @Interface\AddOns\Baggins\Libs\LibBagUtils-1.0\LibBagUtils-1.0.lua:168
myGetContainerNumFreeSlots = <function> defined @Interface\AddOns\Baggins\Libs\LibBagUtils-1.0\LibBagUtils-1.0.lua:183
bags = <table> {
 REAGENTBANK = <table> {
 }
 BAGSBANK = <table> {
 }
 BAGS = <table> {
 }
 BANK = <table> {
 }
}
(*temporary) = <table> {
}
(*temporary) = false
(*temporary) = 2
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "table index is nil"

**Comment by doadin** [comment]
Hopefully this error is fixed in  v3.7.4, whether more will show up or not idk, I do not have tbc access yet. With that in mind you can keep opening tickets if you find more errors, but know I may not be able to fix them yet.
