### ISSUE TITLE
Baggins doesn't override default bags on some new vendors

### ISSUE THREAD

**Issue by WanderingFox** [doadin/Baggins#47]
The baggins option to override default bag showing doesn't seem to catch the new vendors in shadowlands. Specifically the item upgrade vendors and the conduit upgrade table (which seem to call ItemButtonUtil.OpenAndFilterBags and in turn OpenAllBagsMatchingContext as opposed to OpenAllBags)

**Comment by doadin** [comment]
Let me know if you still run into any issues with any vendors.
