### ISSUE TITLE
Keys on keyring always show *new*

### ISSUE THREAD

**Issue by SterlingNerd** [doadin/Baggins#48]
In TBC-Classic baggins LibBagUtil not iterating the keyring bag when tracking new items:
![image](https://user-images.githubusercontent.com/20735173/120351487-c8945c00-c2b4-11eb-9041-b08ec2b910b0.png)

I don't know where the repo for LibBagUtil is, but here's the fix:
![image](https://user-images.githubusercontent.com/20735173/120351597-dcd85900-c2b4-11eb-9d8d-5d479978c37c.png)
![image](https://user-images.githubusercontent.com/20735173/120351625-e3ff6700-c2b4-11eb-87a2-457817e9bdad.png)

**Comment by doadin** [comment]
I've been slowly working on tracking things down, just made a release just a little bit ago but ill push another to pickup the lib change soon. thanks!
