### ISSUE TITLE
da oggi non funziona l'addon

### ISSUE THREAD

**Issue by Ciccouz** [doadin/Baggins#49]
dal upgrade di oggi non si aprono le borse:( NON funziona per niente

**Comment by doadin** [comment]
Hello, sorry to hear, I made several releases today, one of which had an error and would not load, what version do you have now? You may just need to recheck for updates. (also sorry I am trying to google translate) . The current version that should be working is v3.8.3. If you have this version and are still having issue, which version of the game are you playing?(classic, TBC, Retail)

Ciao, scusami, ho fatto diverse versioni oggi, una delle quali aveva un errore e non si caricava, che versione hai adesso? Potrebbe essere solo necessario ricontrollare gli aggiornamenti. (scusa anche se sto provando a tradurre google). La versione corrente che dovrebbe funzionare è la v3.8.3. Se hai questa versione e hai ancora problemi, a quale versione del gioco stai giocando? (classica, da confermare, al dettaglio)

**Comment by uxjw** [comment]
I was having issues yesterday with the addon not loading in 3.8.1, but 3.8.3 is working for me. Thanks for all your hard work on this amazing plugin!

**Comment by doadin** [comment]
@uxjw Yea I too often make release errors, I got to work on that process a bit make it easier for testing. The newest versions work pretty good I'm kind of happy where v3.9.5 has ended, Honestly there was a issue and for the lonest time even with another addon I didn't know what was happening, lua not too complicated interacting with the WoW client, it can be odd sometimes. Ill leave this open for a couple more days in case there is still any issues and then ill close it.

**Comment by Ciccouz** [comment]
Thanks for fixing it now works, the only one I have been using for so many years :)

________________________________
Da: doadin ***@***.***>
Inviato: sabato 5 giugno 2021 02:07
A: doadin/Baggins ***@***.***>
Cc: Ciccouz ***@***.***>; Author ***@***.***>
Oggetto: Re: [doadin/Baggins] da oggi non funziona l'addon (#49)


@uxjw<https://github.com/uxjw> Yea I too often make release errors, I got to work on that process a bit make it easier for testing. The newest versions work pretty good I'm kind of happy where v3.9.5 has ended, Honestly there was a issue and for the lonest time even with another addon I didn't know what was happening, lua not too complicated interacting with the WoW client, it can be odd sometimes. Ill leave this open for a couple more days in case there is still any issues and then ill close it.
