### ISSUE TITLE
Import bag sections from self will cause game not responding.

### ISSUE THREAD

**Issue by wolfcon** [doadin/Baggins#5]
`Import Sections From` this bag self

**Comment by doadin** [comment]
Sorry it got really late for me last night, I just tested:
1. New category 
2. New Bag
3. Section>new section
4. In new section select newly made category

Everything worked fine. Maybe is there a specific category item that is causing a crash? I just tested type bind bind type soulbound.

**Comment by wolfcon** [comment]
1. New category
2. New Bag
3. Section>new section
4. In new `bag` ~`section`~ select newly made category

Problem will got when select newly made cate in bag...instead of new section.

My bad...🤣. Selecting cate in section works fine.
😫But there is a problem causing game not responding that select cate in bad
