### ISSUE TITLE
New search function not working properly?

### ISSUE THREAD

**Issue by TreizeEU** [doadin/Baggins#50]
I just tried out 3.8.3 today, and first noticed it had a built-in search function now. However, it doesn't go away when I close Baggins, and it isn't fitting the Baggins window, so it's stretched several centimeters to the left of the main window (out of the screen as my baggins are on the left edge of the screen)?

**Comment by doadin** [comment]
Is this on classic, retail, TBC?

**Comment by TreizeEU** [comment]
Sorry, Retail.

**Comment by doadin** [comment]
I just loaded on retail and it goes away when closing bags for me, are you getting any errors?

**Comment by doadin** [comment]
in fact before I saw your comment I loaded on retail, classic, and TBC and the search bar closed on all of them when bags closed.

**Comment by TreizeEU** [comment]
I'm not getting any lua errors, I tested with fresh settings file for Baggins and works fine then. After moving them back, minus the baggins_search files, issue still exist.

**Comment by doadin** [comment]
not sure but 0d533ad5eb50315c2e8d0243e49b47781b3a3daf might fix it would you feel comfortable copying the new [Baggins-Search.lua](https://github.com/doadin/Baggins/raw/master/Baggins-Search.lua) from this new commit(that link) and testing? (Don't know why I'm not getting this issue but cant test since I can't replicate)

**Comment by TreizeEU** [comment]
That file helped, now the search bar hides when i close Baggins. It didn't fix the stretchy thing (see screenshot).
![baggins-search](https://user-images.githubusercontent.com/57756419/120615462-99b6eb00-c458-11eb-8627-1c35e69a746b.jpg)

**Comment by doadin** [comment]
ew, interesting, I didn't try the all in one setup, only the individual bags. Thanks for testing Ill look into that size issue now.

**Comment by TreizeEU** [comment]
Eww, indeed. It doesn't help when I have the all in one bag window snapped to the left side of the screen, hiding the most important part of the search bar. :P

**Comment by doadin** [comment]
Another interesting one, I just loaded into the game changed to the allinonesorted preset and the search bar is normal for me. Even tried changing baggins scale and the search bar updated with it. Got to love these issues that only happen for some people.... *sigh*

**Comment by TreizeEU** [comment]
Yeah, when I moved the savedvariables files to my desktop, the searchbar weren't stretched. 

Perhaps this helps?

[Baggins-search.zip](https://github.com/doadin/Baggins/files/6590337/Baggins-search.zip)

**Comment by doadin** [comment]
@agentschmitt any idea? (hope you don't mind the tag)

**Comment by doadin** [comment]
I pushed out another change not sure if it will help.

**Comment by doadin** [comment]
I think I made some significant progress last night I think v3.8.9, is a pretty good one. Let me know how it works out. Thanks!

**Comment by TreizeEU** [comment]
This issue seems fixed now with versions 3.8.9 and onwards, I'm currently on 3.9.2. Thanks for the help.

**Comment by doadin** [comment]
Nice, always weird when I can replicate glad its fixed, and thanks for the help!
