### ISSUE TITLE
Disable Search?

### ISSUE THREAD

**Issue by WanderingFox** [doadin/Baggins#51]
There's no way that I can see to disable the new search frame. I have my bag categories split out very specifically and the new search frame just adds a ton of extra space that I don't want.

It'd be awesome if there was a setting option for whether or not search should be enabled. Alternatively, if you don't want to allow disabling completely, could you instead add an option to pick which bag it shows on?

**Comment by doadin** [comment]
do you have an image so I could see, The config I use I only see one search box.
That being said though if it showing on multiple for some reason I think making it show on only one is defiantly a good idea, Also having an option to disable search sound like a good idea. Obviously just starting working on search. Let me know any other changes you can think of.

**Comment by doadin** [comment]
There is now an option to disable search in settings.

**Comment by WanderingFox** [comment]
Awesome thanks!

It wasn't that it was on every frame, but rather that the extra frame started pushing my bags horizontally when they used to fit perfectly in a single column.

The ability to disable it is perfect for me since I know where everything is already :)

**Comment by doadin** [comment]
Yea interesting still kind of interesting what it looked like, maybe there is an adjustment I could make to make it look better.  Glad I could help at least a little bit.
