### ISSUE TITLE
Slowdown every 60 seconds (New Item Duration check?)

### ISSUE THREAD

**Issue by ryannotfound** [doadin/Baggins#56]
Small issue discovered with the addon - when many rules and/or items (not sure which) are in place, **every 60 seconds there is an in-game hitch/freeze for about 1 second**. I assume this is due to the "New Item Duration" check whereby new items are reviewed and the "new" flag is unset, but there must be some other processing happening as well to cause the delay. Workaround for this was to just set "New Item Duration" to 0, and no more hitches. I have low level characters which use the same profile and do not suffer this issue, it seems to only occur on my max level characters, so I assume it is a combination of high number of rules and items.

Not sure if this is something that can be fixed, but I personally prefer to see all new items and manually clear them anyway, so not a huge deal for me. Wanted to avoid others ditching this great addon if they experienced it, though, and weren't sure why.

**Comment by doadin** [comment]
wow, got to this rly late but new version released today should be better... sorry so late. If you are still around and using the addon let me know how it works. Thanks!

**Comment by doadin** [comment]
Is this still happening?

**Comment by doadin** [comment]
Closing as I think it may be fixed. If not please reopen.

**Comment by ryannotfound** [comment]
Hey, no longer have an active WoW sub so I cannot test. Thanks for looking into this and fixing for others, though!
