### ISSUE TITLE
TBC Classic: keep getting message in chat:"specialtyTargetBags Item Info true"

### ISSUE THREAD

**Issue by SuHwak** [doadin/Baggins#57]
Hi,

In TBC Classic I keep getting a message in chat:"specialtyTargetBags Item Info true" (repeated instantly 3 times) every time I open my bags (shortcut 'b'). The option 'Override Default Bags' is on. When its off it doesn't display that message, but I like my bags sorted like that.

I clicked every reset button that I could find, but no go. Also reinstalled the add-on, also didn't help.

Please help!

**Comment by doadin** [comment]
Do you get this while on a hunter or warlock?

**Comment by SuHwak** [comment]
As a warlock

**Comment by doadin** [comment]
do you also happen to have the "compress shards option on?"

**Comment by SuHwak** [comment]
It does not matter if I have it on or not. Currently its off. I have not changed any option since resetting.

**Comment by SuHwak** [comment]
All options off in the Compress section, still gives me the 3x repeated error

**Comment by doadin** [comment]
the most helpful thing would be if you could change https://github.com/doadin/Baggins/blob/0b87e329b4193c0430d462267d70f0d15a673ad1/Baggins-ItemOps.lua#L137 to `Baggins:Debug('specialtyTargetBags Item Info', select(1, GetItemInfo(link)))`
(Baggins-ItemOps.lua line 137)
that should make it print the name of the item that is giving the issue.

**Comment by doadin** [comment]
I think its an issue with warlock shards not being in a shard bag.

**Comment by SuHwak** [comment]
This is the extra lines I get now:
specialtyTargetBags Item Info Enchanted Runecloth Bag 2 55 0 Container Enchanting Bag 1 INVTYPE_BAG 133666 10000 1 3 2 254 nil false

I do actually have 3 Enchanted Runecloth bags in my bag (not in a bag slot, but actually in my bag).

Going to check if I put them in the bank, the error goes away.

**Comment by SuHwak** [comment]
So when I put them in the bank, it only shows that error when opening the bank. I'll check tomorrow if I can help pinpoint the error further if you need.

**Comment by doadin** [comment]
ok so it is definitely because of that bag, its just a debug print so not really anything wrong, unless you are having issues other than the text appearing.

**Comment by doadin** [comment]
As long as special bags like that work(it puts items in special bags where appropriately) then theres not anything needed print can just be left out of the code.

**Comment by SuHwak** [comment]
I am actively using a soul bag, but not any of the enchantment bags. they're in inventory (now of the bank). So yeah it started to annoy me so that's why I created this issue. :) What can I change to remove the debug messages?

**Comment by doadin** [comment]
I removed it in a new release just update in curseforge.

**Comment by SuHwak** [comment]
Yes, confirmed fixed :D Thanks!
