### ISSUE TITLE
[Retail] I get 4 lua errors from the latest version (4.0.23)

### ISSUE THREAD

**Issue by TreizeEU** [doadin/Baggins#58]
I get the below lua errors every time I log in:

18x AceLocale-3.0-6: Baggins: Missing entry for 'Compress Shards Items'
[string "@Baggins\Baggins-Options.lua"]:390: in function `RebuildOptions'
[string "@Baggins\Baggins-Options.lua"]:1053: in function `InitOptions'
[string "@Baggins\Baggins-v4.0.23.lua"]:365: in function <Baggins\Baggins.lua:356>
[string "=[C]"]: ?
[string "@DataStore\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@DataStore\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:498: in function `InitializeAddon'
[string "@DataStore\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:623: in function <DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:615>

18x AceLocale-3.0-6: Baggins: Missing entry for 'Show Shards as a single button with a count on it'
[string "@Baggins\Baggins-Options.lua"]:392: in function `RebuildOptions'
[string "@Baggins\Baggins-Options.lua"]:1053: in function `InitOptions'
[string "@Baggins\Baggins-v4.0.23.lua"]:365: in function <Baggins\Baggins.lua:356>
[string "=[C]"]: ?
[string "@DataStore\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@DataStore\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:498: in function `InitializeAddon'
[string "@DataStore\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:623: in function <DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:615>

18x AceLocale-3.0-6: Baggins: Missing entry for 'Compress Ammo Items'
[string "@Baggins\Baggins-Options.lua"]:404: in function `RebuildOptions'
[string "@Baggins\Baggins-Options.lua"]:1053: in function `InitOptions'
[string "@Baggins\Baggins-v4.0.23.lua"]:365: in function <Baggins\Baggins.lua:356>
[string "=[C]"]: ?
[string "@DataStore\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@DataStore\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:498: in function `InitializeAddon'
[string "@DataStore\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:623: in function <DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:615>

18x AceLocale-3.0-6: Baggins: Missing entry for 'Show Ammo as a single button with a count on it'
[string "@Baggins\Baggins-Options.lua"]:406: in function `RebuildOptions'
[string "@Baggins\Baggins-Options.lua"]:1053: in function `InitOptions'
[string "@Baggins\Baggins-v4.0.23.lua"]:365: in function <Baggins\Baggins.lua:356>
[string "=[C]"]: ?
[string "@DataStore\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@DataStore\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:498: in function `InitializeAddon'
[string "@DataStore\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:623: in function <DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:615>

**Comment by doadin** [comment]
shouldn't happen in new update, ecf8c9ac379cbf7e07c06b039f91272b0abd7a1a .

**Comment by TreizeEU** [comment]
I can confirm the 4.0.25 version fixed these lua errors for me. Thanks! :)
