### ISSUE TITLE
Possible to swap to new high-res money icons?

### ISSUE THREAD

**Issue by WanderingFox** [doadin/Baggins#59]
As of 9.1.5 there are new money icons located in an atlas ("coin-gold", "coin-silver", "coin-copper") which are much higher resolution than the old ones.

They can be swapped to by replacing:

```
local goldIcon = frame:CreateTexture("BagginsGoldIcon", "ARTWORK")
goldIcon:SetWidth(16)
goldIcon:SetHeight(16)
goldIcon:SetTexture("Interface\\MoneyFrame\\UI-MoneyIcons")
goldIcon:SetTexCoord(0, 0.25, 0, 1)
```

with:

```
local goldIcon = frame:CreateTexture("BagginsGoldIcon", "ARTWORK")
goldIcon:SetWidth(16)
goldIcon:SetHeight(16)
goldIcon:SetAtlas("coin-gold")
```

etc

old texture: 
![image](https://user-images.githubusercontent.com/2967926/143662640-f4725418-5793-4893-95ed-7107b6c540b8.png)

new texture:
![image](https://user-images.githubusercontent.com/2967926/143662651-13feb78b-4fce-4f2a-98c9-1d5732df56aa.png)

**Comment by doadin** [comment]
Updated: https://github.com/doadin/Baggins/commit/11f87ed276bc7c8e4a3400944c00ffd7d2f04fa1 should be pushed through to curse soon.
