### ISSUE TITLE
Game freezes when opening bags

### ISSUE THREAD

**Issue by Art-III** [doadin/Baggins#61]
Wow now freezes for about 20sec when I try to open my bags.
At the bank, it freezes for so long that it throws an error saying that scripting was taking too long.

Message: ...Ons\Baggins\Libs\LibGratuity-3.0\LibGratuity-3.0-90042.lua:213: script ran too long
Time: Sun Mar 13 13:21:11 2022
Count: 1
Stack: ...Ons\Baggins\Libs\LibGratuity-3.0\LibGratuity-3.0-90042.lua:213: script ran too long
[string "@Interface\AddOns\Baggins\Baggins-Filtering.lua"]:319: in function <Interface\AddOns\Baggins\Baggins-Filtering.lua:290>
[string "@Interface\AddOns\Baggins\Baggins-Filtering.lua"]:369: in function `OnSlotChanged'
[string "@Interface\AddOns\Baggins\Baggins-Filtering.lua"]:280: in function `CheckSlotsChanged'
[string "@Interface\AddOns\Baggins\Baggins-Filtering.lua"]:430: in function `ForceFullUpdate'
[string "@Interface\AddOns\Baggins\Baggins.lua"]:3925: in function `OpenBag'
[string "@Interface\AddOns\Baggins\Baggins.lua"]:3972: in function `OpenAllBags'
[string "@Interface\AddOns\Baggins\Baggins.lua"]:3991: in function <Interface\AddOns\Baggins\Baggins.lua:3988>
[string "=(tail call)"]: ?
[string "@Interface\FrameXML\BankFrame.lua"]:321: in function <Interface\FrameXML\BankFrame.lua:303>
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@Interface\FrameXML\UIParent.lua"]:3017: in function `SetUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:2862: in function `ShowUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:2730: in function <Interface\FrameXML\UIParent.lua:2726>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface\FrameXML\UIParent.lua"]:3582: in function <Interface\FrameXML\UIParent.lua:3561>
[string "=[C]"]: in function `ShowUIPanel'
[string "@Interface\FrameXML\BankFrame.lua"]:428: in function `BankFrame_ShowPanel'
[string "@Interface\FrameXML\BankFrame.lua"]:256: in function `OnEvent'
[string "@Interface\AddOns\Baggins\Baggins.lua"]:508: in function <Interface\AddOns\Baggins\Baggins.lua:506>
[string "=(tail call)"]: ?

**Comment by doadin** [comment]
Do you have new item duration > 0 ?
