### ISSUE TITLE
Feature Request: Learned Profession conditional

### ISSUE THREAD

**Issue by WanderingFox** [doadin/Baggins#63]
Hey there! First all absolutely love this addon! Thank you so much for maintaining it!

I was wondering though if it would be possible to get a "profession learned" conditional?

I'm on a crusade to reduce the number of profiles used in my addons and I can *almost* get down to one profile with baggins, except that I use different profession bag categories on each of my characters (eg. one bag might show alchemy items on one character but blacksmithing on another character). That way I can make a bag that has several categories along the lines of "knows blacksmithing and (normal rules for that category)" and "knows alchemy and (...)" etc.

**Comment by WanderingFox** [comment]
Some digging suggests this should be doable?

ProfessionID -> Localized name can be done via `Constants.ProfessionIDs` and `C_TradeSkillUI.GetTradeSkillLineInfoByID(id)`

I'll try to take a stab at this and see if I can close, not sure how to implement for classic though as I only play retail :(

**Comment by doadin** [comment]
Sorry little late responding, however the function you linked is going to be removed from the game in 10.0, so would not be useful for long. I am going to look into this though.

**Comment by doadin** [comment]
Im not sure how this is going to work, how filters work is it matches an item to a type, I don't know any other way other than to match all items to w.e. profession the character has. I'm going to push a update that adds this now let me know if it works I guess?

**Comment by WanderingFox** [comment]
Update tosses a lua error on first login (presumably because `GetProfessions` isn't available until the player is in the world) :(

After a reload there's no errors, but it doesn't seem to do what I was hoping for.

My hope was that I could create categories like the attached image and that would filter the item into the category, but only if the given profession was learned. Instead it seems to just always filter the item and ignore the `AND`

![image](https://user-images.githubusercontent.com/2967926/189508423-132cbe24-7203-474c-93fc-a3e298eee873.png)

**Comment by doadin** [comment]
I just pushed another update to see if it helps any, if not im not sure I can add this.

**Comment by doadin** [comment]
Just to check are you testing on retail or other game version?

**Comment by doadin** [comment]
I just pushed one more update out unfortunately it only works if you reload once after first login, becuase as you have noted GetProfessions isn't available until the player is in the world. Once I figure out how to update the cat after login it should work but I have yet to figure that out.

**Comment by doadin** [comment]
ok I just pushed v4.0.57 I think this version works, let me know.

**Comment by WanderingFox** [comment]
Works!

Though something is up with the item category filter and it's choking on `IsWrathWow` which doesn't exist.

Manually defining it in baggins.lua in the same way as the other ones that already exist fixes that :)

```
local WOW_PROJECT_WRATH_CLASSIC = _G.WOW_PROJECT_WRATH_CLASSIC

. . .

function Baggins:IsWrathWow() --luacheck: ignore 212
	return WOW_PROJECT_ID == WOW_PROJECT_WRATH_CLASSIC
end
```

**Comment by doadin** [comment]
I had it typed out but in trying to fix add this feature I was up late and forgot to push that commit, sorry that fix should be going out now.

**Comment by doadin** [comment]
Since this feature works now I am going to go ahead and close this, thank you for your help and support!
