### ISSUE TITLE
LUA errors on launch: attempt to call method 'IsWrathWow' (a nil value)

### ISSUE THREAD

**Issue by Elberet** [doadin/Baggins#64]
Baggins version: 4.0.57-wrath
Obtained from: CurseForge
WoW version: WotLK Classic 3.4.0.45506
Game language: de

The stacktrace is disappointingly short:
```
[string \"@Interface\AddOns\Baggins\src\filters\ItemType.lua\"]:106: in main chunk
```

I'm in no way a LUA expert, but it appears that the referenced method declaration is missing from `Baggins.lua`.

**Comment by doadin** [comment]
I had it typed out but in trying to fix adding a feature that was requested I was up late and forgot to push that commit, sorry that fix should be going out now.
