### ISSUE TITLE
LUA error on launch: attempt to call upvalue 'GetProfessions' (a nil value)

### ISSUE THREAD

**Issue by Elberet** [doadin/Baggins#65]
Baggins version: 4.0.57-wrath
Obtained from: CurseForge
WoW version: WotLK Classic 3.4.0.45506
Game language: de

Stacktrace:
```
[string \"@Interface\AddOns\Baggins\src\filters\Profession.lua\"]:39: in function <Interface\AddOns\Baggins\src\filters\Profession.lua:36>
```

Apparently, the `GetProfessions` API function was added in Cataclysm (game version 4.0.1), so this filter needs additional work or should be disabled for WotLK Classic.

**Comment by doadin** [comment]
Yes that feature is the one I was up late trying to add. It indeed needs some changes to be able to work in non-retail game versions for now I have pushed an update to disable it till I have time to fix it. Thanks! 
https://github.com/doadin/Baggins/commit/bd0e4df2dc28cd4cf438893dcfdee0c19d4a7ee5
