### ISSUE TITLE
4.1.2 will not load even as the only addon

### ISSUE THREAD

**Issue by jamesbearclaw** [doadin/Baggins#67]
There are all kinds of errors and none of them relate to one another.  It sort of looks like it's not loading ACE as the reference is to the version in Kaliel's Tracker (which I do have, but not loaded).

Is it possible something didn't get bundled in?

**Comment by doadin** [comment]
Sorry this is an issue with changes I made in prep for the next retail xpack DF, I have reverted this change and pushed out a new version if you dont want to wait for the you can download the 4.1.1 from github or curseforge in the mean time.

**Comment by Stefanbrodd** [comment]
4.1.3-wrath seems broken too, it's loading but no bags show.

**Comment by doadin** [comment]
@Stefanbrodd @jamesbearclaw Sorry I made a few mistakes im working on improving my workflow v4.1.5 should be working.

**Comment by doadin** [comment]
Closing this as fixed if there are still issue please reopen or make a new issue if unrelated.
