### ISSUE TITLE
Retail - All screen elements hidden

### ISSUE THREAD

**Issue by ryannotfound** [doadin/Baggins#71]
Strange issue as of recent update(s) - all screen elements will be hidden. I have to alt+z twice to show all screen elements again.

This occurs with all other addons disabled, so I know it's Baggins. This is reproduceable by modifying Bag/Category configurations, although I don't know what specific combinations do this (attempts to find a repeatable pattern did not yield results).

I had to reset my entire profile due to this occurring when loading my character and then again when simply when opening bags. Following the profile reset it did not do this when opening bags, only when modifying Bags/Categories (i had to start from scratch), so it was probably something with my profile which became out of date due to changes in v10.x of WoW.

**Comment by doadin** [comment]
Still working on fixing retail please let me know if you continue to have issues after v4.4.4 .

**Comment by ryannotfound** [comment]
will do!

**Comment by ryannotfound** [comment]
Still occurring with v4.4.4.

Found a way to reproduce this 100%. With a default profile (i simply performed a profile reset to "default"), go to Bag/Category Config. Under Bags, click Other (the main default bag) and click the New Section button 12 times. All screen elements will hide, forcing you to alt+z twice to re-show them. FWIW any combination of add/remove sections will produce this same issue (example, add 6, then delete the 6 sections you added), but it always hides at 12. Strange, but hope this helps.

**Comment by doadin** [comment]
I am almost 100% certain it is the toy or tooltip filter. They use a LibGratuity-3.0 to scan tooltips which has not been updated since 2014. And with recent changes to retail it broke. Apparently my if for this is causing some issues, looking into it.

**Comment by doadin** [comment]
ok I think the tooltip scanning should work in v4.4.6, let me know if that one still has issues I am working on fixing search as well.

**Comment by ryannotfound** [comment]
looks good - unable to reproduce, thanks!
