### ISSUE TITLE
Retail - alt+Right click menu does not work on items

### ISSUE THREAD

**Issue by ryannotfound** [doadin/Baggins#74]
Title - error below:

5x Interface/AddOns/Baggins/Baggins.lua:2453: attempt to call upvalue 'GetContainerItemID' (a nil value)
[string "@Interface/AddOns/Baggins/Baggins.lua"]:2453: in function <Interface/AddOns/Baggins/Baggins.lua:2423>

Locals:
button = BagginsPooledItemButton77 {
 0 = <userdata>
 OnLeave = <function> defined @Interface/FrameXML/ContainerFrame.lua:1478
 SetItem = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:544
 IconOverlay = Texture {
 }
 slots = <table> {
 }
 SetAlpha = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:631
 UpdateCooldown = <function> defined @Interface/FrameXML/ContainerFrame.lua:1685
 showMatchHighlight = true
 OnDragStart = <function> defined @Interface/FrameXML/ContainerFrame.lua:1576
 OnReceiveDrag = <function> defined @Interface/FrameXML/ContainerFrame.lua:1580
 icon = BagginsPooledItemButton77IconTexture {
 }
 UpdateTooltip = <function> defined @Interface/AddOns/Baggins/Baggins.lua:2065
 SetReadable = <function> defined @Interface/FrameXML/ContainerFrame.lua:1677
 CheckUpdateTooltip = <function> defined @Interface/FrameXML/ContainerFrame.lua:1701
 UpdateNewItem = <function> defined @Interface/FrameXML/ContainerFrame.lua:1627
 IsReadable = <function> defined @Interface/FrameXML/ContainerFrame.lua:1681
 count = 1
 UpdateItemContextMatching = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:450
 SetItemButtonCount = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:614
 SetItemInternal = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:549
 UpdateCraftedProfessionsQualityShown = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:461
 PostOnShow = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:414
 GetItemContextOverlayMode = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:471
 SetItemSource = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:528
 IconQuestTexture = BagginsPooledItemButton77IconQuestTexture {
 }
 hasItem = 1
 SetBagID = <function> defined @Interface/FrameXML/ContainerFrame.lua:1584
 IsExtended = <function> defined @Interface/FrameXML/ContainerFrame.lua:1715
 UpdateItemContextOverlay = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:488
 CheckForTutorials = <function> defined @Interface/FrameXML/ContainerFrame.lua:1744
 newtext = BagginsPooledItemButton77NewText {
 }
 emptyBackgroundAtlas = "bags-item-slot64"
 Count = BagginsPooledItemButton77Count {
 }
 SetItemButtonAnchorPoint = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:618
 searchOverlay = BagginsPooledItemButton77SearchOverlay {
 }
 GetItemLocation = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:610
 IconOverlay2 = Texture {
 }
 OnModifiedClick = <function> defined @Interface/FrameXML/ContainerFrame.lua:1535
 UpdateItemContextOverlayTextures = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:499
 OnItemContextChanged = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:410
 UpdateExtended = <function> defined @Interface/FrameXML/ContainerFrame.lua:1719
 SetItemButtonQuality = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:658
 UpdateJunkItem = <function> defined @Interface/FrameXML/ContainerFrame.lua:1655
 HasItem = <function> defined @Interface/FrameXML/ContainerFrame.lua:1673
 OnClick = <function> defined @Interface/FrameXML/ContainerFrame.lua:1448
 itemContextMatchResult = 3
 glow = Texture {
 }
 GetDebugReportInfo = <function> defined @Interface/FrameXML/ContainerFrame.lua:1228
 timeSinceUpgradeCheck = 0
 flashAnim = AnimationGroup {
 }
 newitemglowAnim = AnimationGroup {
 }
 NormalTexture = BagginsPooledItemButton77NormalTexture {
 }
 SetItemButtonScale = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:623
 JunkIcon = Texture {
 }
 ExtendedSlot = Texture {
 }
 PostOnHide = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:423
 UpgradeIcon = Texture {
 }
 BattlepayItemTexture = Texture {
 }
 NewItemTexture = Texture {
 }
 flash = Texture {
 }
 Cooldown = BagginsPooledItemButton77Cooldown {
 }
 IconBorder = Texture {
 }
 OnUpdate = <function> defined @Interface/FrameXML/ContainerFrame.lua:1489
 UpdateQuestItem = <function> defined @Interface/FrameXML/ContainerFrame.lua:1615
 SetItemButtonTexture = <function> defined @In

**Comment by doadin** [comment]
Fixed: https://github.com/doadin/Baggins/commit/02be45664cbeafff35be82c1bd5be55bfff22d5f

**Comment by ryannotfound** [comment]
this also appears broken - v4.4.9 and getting errors below:

11x Interface/AddOns/Baggins/Baggins.lua:2453: attempt to call upvalue 'GetContainerItemID' (a nil value)
[string "@Interface/AddOns/Baggins/Baggins.lua"]:2453: in function <Interface/AddOns/Baggins/Baggins.lua:2423>

Locals:
button = BagginsPooledItemButton77 {
 0 = <userdata>
 OnLeave = <function> defined @Interface/FrameXML/ContainerFrame.lua:1478
 SetItem = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:544
 IconOverlay = Texture {
 }
 slots = <table> {
 }
 SetAlpha = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:631
 UpdateCooldown = <function> defined @Interface/FrameXML/ContainerFrame.lua:1685
 showMatchHighlight = true
 OnDragStart = <function> defined @Interface/FrameXML/ContainerFrame.lua:1576
 OnReceiveDrag = <function> defined @Interface/FrameXML/ContainerFrame.lua:1580
 icon = BagginsPooledItemButton77IconTexture {
 }
 UpdateTooltip = <function> defined @Interface/AddOns/Baggins/Baggins.lua:2065
 SetReadable = <function> defined @Interface/FrameXML/ContainerFrame.lua:1677
 CheckUpdateTooltip = <function> defined @Interface/FrameXML/ContainerFrame.lua:1701
 UpdateNewItem = <function> defined @Interface/FrameXML/ContainerFrame.lua:1627
 IsReadable = <function> defined @Interface/FrameXML/ContainerFrame.lua:1681
 count = 1
 UpdateItemContextMatching = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:450
 SetItemButtonCount = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:614
 SetItemInternal = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:549
 UpdateCraftedProfessionsQualityShown = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:461
 PostOnShow = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:414
 GetItemContextOverlayMode = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:471
 SetItemSource = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:528
 IconQuestTexture = BagginsPooledItemButton77IconQuestTexture {
 }
 hasItem = 1
 SetBagID = <function> defined @Interface/FrameXML/ContainerFrame.lua:1584
 IsExtended = <function> defined @Interface/FrameXML/ContainerFrame.lua:1715
 UpdateItemContextOverlay = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:488
 CheckForTutorials = <function> defined @Interface/FrameXML/ContainerFrame.lua:1744
 newtext = BagginsPooledItemButton77NewText {
 }
 emptyBackgroundAtlas = "bags-item-slot64"
 Count = BagginsPooledItemButton77Count {
 }
 SetItemButtonAnchorPoint = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:618
 searchOverlay = BagginsPooledItemButton77SearchOverlay {
 }
 GetItemLocation = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:610
 IconOverlay2 = Texture {
 }
 OnModifiedClick = <function> defined @Interface/FrameXML/ContainerFrame.lua:1535
 UpdateItemContextOverlayTextures = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:499
 OnItemContextChanged = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:410
 UpdateExtended = <function> defined @Interface/FrameXML/ContainerFrame.lua:1719
 SetItemButtonQuality = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:658
 UpdateJunkItem = <function> defined @Interface/FrameXML/ContainerFrame.lua:1655
 HasItem = <function> defined @Interface/FrameXML/ContainerFrame.lua:1673
 OnClick = <function> defined @Interface/FrameXML/ContainerFrame.lua:1448
 itemContextMatchResult = 3
 glow = Texture {
 }
 GetDebugReportInfo = <function> defined @Interface/FrameXML/ContainerFrame.lua:1228
 timeSinceUpgradeCheck = 0
 flashAnim = AnimationGroup {
 }
 newitemglowAnim = AnimationGroup {
 }
 NormalTexture = BagginsPooledItemButton77NormalTexture {
 }
 SetItemButtonScale = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:623
 JunkIcon = Texture {
 }
 ExtendedSlot = Texture {
 }
 PostOnHide = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:423
 UpgradeIcon = Texture {
 }
 BattlepayItemTexture = Texture {
 }
 NewItemTexture = Texture {
 }
 flash = Texture {
 }
 Cooldown = BagginsPooledItemButton77Cooldown {
 }
 IconBorder = Texture {
 }
 OnUpdate = <function> defined @Interface/FrameXML/ContainerFrame.lua:1489
 UpdateQuestItem = <function> defined @Interface/FrameXML/ContainerFrame.lua:1615
 SetItemButtonTexture = <function> defined @In

**Comment by doadin** [comment]
in 4.5.0
