### ISSUE TITLE
Compressing all or empty slots compresses everything into a single slot, hiding everything but one item per category

### ISSUE THREAD

**Issue by Elberet** [doadin/Baggins#75]
When enabling stack compression, Baggins compresses all slots in a category into a single slot, even if they are not stacks of the same item. For example:

No compression:
![grafik](https://user-images.githubusercontent.com/361662/202580056-63f3a7bb-c77f-46e3-b36d-91d9313ab65a.png)

With "compress empty slots" enabled:
![grafik](https://user-images.githubusercontent.com/361662/202580181-d4c40681-a53b-4866-9f1a-06c77f3bc823.png)

This error occurrs with Baggins v4.5.0 on Wrath Classic with a German localized game client.

**Comment by Molbork** [comment]
Same issue with yesterday's update, did a full reset even and it's still there. Hiding other since it was huge in the uncompressed picture.
![image](https://user-images.githubusercontent.com/50129786/202599476-391db55b-bb0c-4382-8a0f-f005593ccfde.png)

disabling bag compression
![image](https://user-images.githubusercontent.com/50129786/202599431-09ddda8f-4cd4-41ff-9fdf-2b2099542532.png)

**Comment by doadin** [comment]
hmm in that one screen shot the count of the items is right. And in both theres items not shown thats weird. Are both of those wrath classic? @Elberet @Molbork

**Comment by Elberet** [comment]
I should probably have put this at the top of the post rather than below the screenshots, but:

> This error occurrs with Baggins v4.5.0 on Wrath Classic with a German localized game client.

**Comment by doadin** [comment]
v4.3.0 seems to be a good working version, now I just have to narrow it down to which version introduces the issue.

**Comment by doadin** [comment]
seems like 4.3.5 works 4.3.6+ does NOT.

**Comment by doadin** [comment]
Found the issue I didn't set a variable for classic versions, v4.5.2 should work.

**Comment by Elberet** [comment]
Can confirm, v4.5.2 fixes this issue! 😄

**Comment by doadin** [comment]
Yea they changed the game to match with retail, so I sent out another set of changes v4.8.0 with more of the updates like I had to do to retail. Still might need more not sure.
