### ISSUE TITLE
(WOTLK) Using "Tooltip" for a Item Category is broken.

### ISSUE THREAD

**Issue by Runkel79** [doadin/Baggins#77]
Addon Version: 11/18/2022 Baggins-v4.5.2-wrath.zip

Error: The Plugin providing this rule is out of date and not compatible with Baggins-2.0

Was working fine in Version: 11/15/2022 Baggins-v4.3.0-wrath.zip

**Comment by doadin** [comment]
should be fixed: https://github.com/doadin/Baggins/commit/bd4e4cf1107ed5ccbae21889788b9a045d5f0097

**Comment by doadin** [comment]
look for v4.5.6
