### ISSUE TITLE
LUA Error when editing Categories

### ISSUE THREAD

**Issue by Runkel79** [doadin/Baggins#78]
WOTLK Classic, latest version.

This is what Bugsack caught

13x Baggins\src\filters\ItemType.lua:226: attempt to call upvalue 'GetAuctionItemSubClasses' (a nil value)
[string "@Baggins\src\filters\ItemType.lua"]:226: in function `member'
[string "@Masque\Libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-86.lua"]:215: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:164>
[string "@Masque\Libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-86.lua"]:1226: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1110>
[string "@Masque\Libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-86.lua"]:1137: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1110>
[string "@Masque\Libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-86.lua"]:1639: in function `FeedGroup'
[string "@Masque\Libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-86.lua"]:1564: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1548>
[string "=[C]"]: ?
[string "@Questie\Libs\AceGUI-3.0\AceGUI-3.0-41.lua"]:72: in function <Questie\Libs\AceGUI-3.0\AceGUI-3.0.lua:70>
[string "@Questie\Libs\AceGUI-3.0\AceGUI-3.0-41.lua"]:306: in function `Fire'
[string "@!KalielsTracker\Libs\AceGUI-3.0-41\widgets\AceGUIContainer-TreeGroup.lua"]:508: in function `SetSelected'
[string "@!KalielsTracker\Libs\AceGUI-3.0-41\widgets\AceGUIContainer-TreeGroup.lua"]:185: in function <...ibs\AceGUI-3.0\widgets\AceGUIContainer-TreeGroup.lua:181>

**Comment by doadin** [comment]
Fixed: https://github.com/doadin/Baggins/commit/1c72d5f4a1324d09708eb080999506c2dc3806b5
This fix is included in v4.5.9 .
