### ISSUE TITLE
Opening bag error

### ISSUE THREAD

**Issue by Weetbix813** [doadin/Baggins#79]
Error on opening bags:

33x Baggins/Baggins.lua:3130: attempt to compare number with nil
[string "@Baggins/Baggins.lua"]:3130: in function `UpdateItemButton'
[string "@Baggins/Baggins.lua"]:1916: in function `ReallyLayoutSection'
[string "@Baggins/Baggins.lua"]:757: in function `?'
[string "@Baggins/Baggins.lua"]:171: in function <Baggins/Baggins.lua:163>

Locals:
self = <table> {
 cannotDetachTooltip = true
 modules = <table> {
 }
 CancelTimer = <function> defined @DataStore/libs/AceTimer-3.0/AceTimer-3.0.lua:147
 CreateItemButton = <function> defined @Baggins/Baggins.lua:2509
 GetIncludeRule = <function> defined @Baggins/Baggins-Filtering.lua:462
 RemoveSection = <function> defined @Baggins/Baggins.lua:3850
 GetCachedItem = <function> defined @Baggins/Baggins-Filtering.lua:534
 OptimizeSectionLayout = <function> defined @Baggins/Baggins.lua:1564
 UpdateSectionContents = <function> defined @Baggins/Baggins.lua:1195
 IsAnyBankOpen = <function> defined @Baggins/Baggins.lua:4126
 RemoveRule = <function> defined @Baggins/Baggins.lua:3867
 OnTextUpdate = <function> defined @Baggins/Baggins.lua:3590
 InitOptions = <function> defined @Baggins/Baggins-Options.lua:1050
 ScheduleTimer = <function> defined @DataStore/libs/AceTimer-3.0/AceTimer-3.0.lua:94
 UpdateDB = <function> defined @Baggins/Baggins-Options.lua:1031
 GetBagTypes = <function> defined @Baggins/Baggins-Filtering.lua:89
 UpdateItemButtons = <function> defined @Baggins/Baggins.lua:2974
 LayoutSection = <function> defined @Baggins/Baggins.lua:1854
 OnBankOpened = <function> defined @Baggins/Baggins.lua:708
 SetEnabledState = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:420
 Hook = <function> defined @Baggins/Libs/AceHook-3.0/AceHook-3.0.lua:273
 RegisterSkin = <function> defined @Baggins/Baggins-Skins.lua:32
 InitBagCategoryOptions = <function> defined @Baggins/Baggins-Options.lua:3560
 UpdateLayout = <function> defined @Baggins/Baggins.lua:2963
 CountNormalSlots = <function> defined @Baggins/Baggins.lua:3678
 AddCustomRule = <function> defined @Baggins/Baggins-Filtering.lua:101
 RuleTypeIterator = <function> defined @Baggins/Baggins-Filtering.lua:123
 NewModule = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:231
 MoveBag = <function> defined @Baggins/Baggins.lua:3764
 ForceFullRefresh = <function> defined @Baggins/Baggins-Filtering.lua:430
 DoRecheckCompress = <function> defined @Baggins/Baggins-ItemOps.lua:224
 GetAce3Opts = <function> defined @Baggins/Baggins-Filtering.lua:152
 GetName = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:275
 MoveRule = <function> defined @Baggins/Baggins.lua:3799
 defaultcategories = <table> {
 }
 ClearSectionCaches = <function> defined @Baggins/Baggins.lua:994
 Disable = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:310
 CategoryMatchRemoved = <function> defined @Baggins/Baggins.lua:866
 Unhook = <function> defined @Baggins/Libs/AceHook-3.0/AceHook-3.0.lua:417
 CloseSpecialWindows = <function> defined @Baggins/Baggins.lua:4160
 CreateBagPlacementFrame = <function> defined @Baggins/Baggins.lua:1973
 IncludeItemInCategory = <function> defined @Baggins/Baggins-Filtering.lua:494
 Debug = <function> defined @Baggins/Baggins.lua:114
 CategoryMatchAdded = <function> defined @Baggins/Baggins.lua:806
 FireSignal = <function> defined @Baggins/Baggins.lua:194
 IsActive = <function> defined @Baggins/Baggins.lua:387
 CountAmmoSlots = <function> defined @Baggins/Baggins.lua:3682
 SlotMoved = <function> defined @Baggins/Baggins.lua:905
 SetDefaultModuleLibraries = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:363
 Baggins_CategoriesChanged = <func

**Comment by doadin** [comment]
Is this retail or wrath or classic?

**Comment by Weetbix813** [comment]
Oh sorry, this is retail!

Dr. Rochelle M. Burnaford
She/her pronouns<http://www.transstudent.org/pronouns101/>
Psychology Area Convener 2022-2023
Professor of Psychology
Diablo Valley College

"I am not free while any woman is unfree,
even when her shackles are very different
from my own."
-Audre Lorde

**Comment by Weetbix813** [comment]
This is retail!

**Comment by doadin** [comment]
Thank you! I have not run into this issue myself, however I have pushed an update out just now v4.6.1. This version should hopefully fix this error. This error has to do with quality colors on items, if you notice any issue with items not having the proper quality color please let me know, and I will look into it further.

**Comment by Weetbix813** [comment]
Thank you! seems to have fixed, I'll keep an eye on the coloring :)

**Comment by doadin** [comment]
Thank you! I am going to close this, but If you need anything else feel free to reopen this issue or make another!
