### ISSUE TITLE
Item Count Wrong on Compressed Stacks (WOTLK)

### ISSUE THREAD

**Issue by Runkel79** [doadin/Baggins#80]
Very weird bug i just noticed.

I got 40 Potions of speed, 40 Runic Mana Injectors, 40 Honeymint Tea, 40 Buff Food and for each of them it only Shows 30 when compressed.

P.S. No LUA Errors, it just displays the wrong value

Update: i kept playing and it looks like the wrong item count changes at will, now it shows 31 instead of the correct value.

**Comment by Runkel79** [comment]
![WowClassic_eIJHnL4JJR](https://user-images.githubusercontent.com/22620131/203485928-2018f462-df9f-41b3-9909-37418a73dfc8.png)
![WowClassic_k9BeVXWJlU](https://user-images.githubusercontent.com/22620131/203485957-558c226c-4f5c-4629-b04e-5e8d4be13e18.png)

**Comment by Runkel79** [comment]
Another Example Compressed/Uncompressed

![WowClassic_LXzD7ZIiR6](https://user-images.githubusercontent.com/22620131/203487082-68f7ddb5-bd2b-446f-990e-54a14510384d.png)
![WowClassic_Cx8JX9JdCC](https://user-images.githubusercontent.com/22620131/203487105-f3cb3571-5d42-4276-8770-3b4306cbdf57.png)

**Comment by doadin** [comment]
Does it ever show the right count when compress, for example when you first login?

**Comment by Runkel79** [comment]
I already rolled back but i reinstalled the latest Version and the answer is no, at the moment the compressed count is eight instead of the correct value

**Comment by Runkel79** [comment]
And i just got this LUA Error:

`4x Interface\AddOns\Baggins\Baggins-v4.6.2.lua:1453: invalid order function for sorting
[string "=[C]"]: ?
[string "@Interface\AddOns\Baggins\Baggins-v4.6.2.lua"]:1453: in function `SortItemList'
[string "@Interface\AddOns\Baggins\Baggins-v4.6.2.lua"]:1210: in function `UpdateSectionContents'
[string "@Interface\AddOns\Baggins\Baggins-v4.6.2.lua"]:1131: in function `UpdateSection'
[string "@Interface\AddOns\Baggins\Baggins-v4.6.2.lua"]:1106: in function `ReallyUpdateBags'
[string "@Interface\AddOns\Baggins\Baggins-v4.6.2.lua"]:751: in function `?'
[string "@Interface\AddOns\Baggins\Baggins-v4.6.2.lua"]:171: in function <Interface\AddOns\Baggins\Baggins.lua:163>

Locals:
(*temporary) = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
}
(*temporary) = <function> defined @Interface\AddOns\Baggins\Baggins.lua:1324
(*temporary) = <table> {
 slotcount = 1
 slots = <table> {
 }
 itemid = 30688
}
(*temporary) = <table> {
 slotcount = 1
 slots = <table> {
 }
 itemid = 11136
}
(*temporary) = nil
`

**Comment by doadin** [comment]
was a simple typo I didn't notice, oops, soooo sorry.
Fixed: ffc86cbf71996b5858c56ee7f27b6d6d2e19e78f
