### ISSUE TITLE
Rule Broken (WOTLK)

### ISSUE THREAD

**Issue by Runkel79** [doadin/Baggins#81]
Found another Bug, it looks like the "Bind" Rule is broken. There is no LUA error message related to this bug.

I have a custom category for items I want to send to my bank character to sell on the Auction House, it looks like this:

![WowClassic_lvHZdh8Tmw](https://user-images.githubusercontent.com/22620131/203670378-ea63f297-16c5-4000-a1b0-0ea8af42b3ad.png)

and a very similar category for soulbound items with "and -> bind -> soulbound" for quick and easy disenchanting/vendoring.

Worked fine in Baggins-v4.3.0-wrath, but is currently not functional.

**Comment by doadin** [comment]
<img width="923" alt="image" src="https://user-images.githubusercontent.com/2148359/203715221-d08f5a73-19bf-4d2e-bf21-4bcb444588aa.png">
Is there a specific bind type you are having issue with? I just tested v4.6.2 and thats what I got

**Comment by doadin** [comment]
I did notice BoP is missing I am adding that now.

**Comment by doadin** [comment]
ok BoP is essential soulbound so nott needed but I added it anyways, and upon further investigation I found soulbound was not working I have added a fix for this.
2f50cd89ddab4d2e8f9cc1f622353eb669e1b3c3

Let me know if you have any other issues. Look for v4.6.3 .
