### ISSUE TITLE
Item Level not displayed in german (maybe also in other) language

### ISSUE THREAD

**Issue by tanrak** [doadin/Baggins#82]
When I set the language in the game to German, the item level is not displayed. If I set it back to English the item level is shown. Tested at wrath classic and retail.

**Comment by xozion** [comment]
Can confirm this issue. Happening in Retail WoW 10.0.2 (46924) in German with Baggins 4.7.5

**Comment by doadin** [comment]
@tanrak @xozion Fixed: 7ca4a49e463e5c28e60fffd2d96e40c806eb6142 , this fix is included in v4.7.6 .
