### ISSUE TITLE
Right-Click menu error in bank

### ISSUE THREAD

**Issue by ryannotfound** [doadin/Baggins#85]
Error when alt-clicking an item stored in bank. Easily reproduceable. This does not seem to affect functionality of right-click menu, but does throw an error.

---

48x Baggins/Baggins.lua:2139: attempt to concatenate field 'owner' (a nil value)
[string "@Baggins/Baggins.lua"]:2139: in function <Baggins/Baggins.lua:2134>
[string "@Baggins/Baggins.lua"]:2176: in function <Baggins/Baggins.lua:2171>
[string "@Baggins/Baggins.lua"]:2470: in function <Baggins/Baggins.lua:2421>

Locals:
(*temporary) = <function> defined @Baggins/Libs/AceHook-3.0/AceHook-3.0.lua:417
(*temporary) = <table> {
 cannotDetachTooltip = true
 modules = <table> {
 }
 CancelTimer = <function> defined @Baggins/Libs/AceTimer-3.0/AceTimer-3.0.lua:147
 CreateItemButton = <function> defined @Baggins/Baggins.lua:2507
 GetIncludeRule = <function> defined @Baggins/Baggins-Filtering.lua:463
 RemoveSection = <function> defined @Baggins/Baggins.lua:3843
 GetCachedItem = <function> defined @Baggins/Baggins-Filtering.lua:535
 OptimizeSectionLayout = <function> defined @Baggins/Baggins.lua:1564
 UpdateSectionContents = <function> defined @Baggins/Baggins.lua:1195
 IsAnyBankOpen = <function> defined @Baggins/Baggins.lua:4119
 RemoveRule = <function> defined @Baggins/Baggins.lua:3860
 OnTextUpdate = <function> defined @Baggins/Baggins.lua:3583
 InitOptions = <function> defined @Baggins/Baggins-Options.lua:1050
 ScheduleTimer = <function> defined @Baggins/Libs/AceTimer-3.0/AceTimer-3.0.lua:94
 UpdateDB = <function> defined @Baggins/Baggins-Options.lua:1031
 GetBagTypes = <function> defined @Baggins/Baggins-Filtering.lua:89
 UpdateItemButtons = <function> defined @Baggins/Baggins.lua:2972
 LayoutSection = <function> defined @Baggins/Baggins.lua:1854
 OnBankOpened = <function> defined @Baggins/Baggins.lua:708
 SetEnabledState = <function> defined @!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:420
 Hook = <function> defined @Baggins/Libs/AceHook-3.0/AceHook-3.0.lua:273
 RegisterSkin = <function> defined @Baggins/Baggins-Skins.lua:34
 InitBagCategoryOptions = <function> defined @Baggins/Baggins-Options.lua:3560
 UpdateLayout = <function> defined @Baggins/Baggins.lua:2961
 CountNormalSlots = <function> defined @Baggins/Baggins.lua:3671
 AddCustomRule = <function> defined @Baggins/Baggins-Filtering.lua:101
 RuleTypeIterator = <function> defined @Baggins/Baggins-Filtering.lua:123
 NewModule = <function> defined @!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:231
 MoveBag = <function> defined @Baggins/Baggins.lua:3757
 ForceFullRefresh = <function> defined @Baggins/Baggins-Filtering.lua:431
 DoRecheckCompress = <function> defined @Baggins/Baggins-ItemOps.lua:224
 GetAce3Opts = <function> defined @Baggins/Baggins-Filtering.lua:152
 GetName = <function> defined @!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:275
 MoveRule = <function> defined @Baggins/Baggins.lua:3792
 defaultcategories = <table> {
 }
 ClearSectionCaches = <function> defined @Baggins/Baggins.lua:994
 Disable = <function> defined @!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:310
 CategoryMatchRemoved = <function> defined @Baggins/Baggins.lua:866
 Unhook = <function> defined @Baggins/Libs/AceHook-3.0/AceHook-3.0.lua:417
 CloseSpecialWindows = <function> defined @Baggins/Baggins.lua:4153
 CreateBagPlacementFrame = <function> defined @Baggins/Baggins.lua:1973
 IncludeItemInCategory = <function> defined @Baggins/Baggins-Filtering.lua:495
 Debug = <function> defined @Baggins/Baggins.lua:114
 CategoryMatchAdded = <function> defined @Baggins/Baggins.lua:806
 FireSignal = <function> defined @Baggins/Baggins.lua:194
 IsActive = <function> defined @Baggins/Baggins.lua:387
 CountAmmoSlots = <function> defined @Baggins/Baggins.lua:3675
 SlotMoved = <function> defined @Baggins/Baggins.lua:905
 SetDefaultModuleLibrari

**Comment by doadin** [comment]
Fixed: e40af9512dee82ab5e6ba963a834b9df895166fb
Fix included in v4.6.7 .
