### ISSUE TITLE
Default bag opens when clicking on looted item, and then bags don't close

### ISSUE THREAD

**Issue by UnavengedAvo** [doadin/Baggins#89]
I have run into a weird bug where if I click on the loot popup to view an item in my bags, it opens the default bags, and then I am unable to close the bags.

I have tried everything including macro commands, but nothing seems to close it other then a UI reload.

**Comment by doadin** [comment]
Is this retail, wrath, classic?

**Comment by UnavengedAvo** [comment]
My apologies, I was referring to retail.

**Comment by doadin** [comment]
Unfortunately I am unable to replicate this fully. I see that clicking loot does open default bag the loot is in however I am able to close the bags with the "x"/close button, the key bind default "b" obviously wont work if you have override default on.

**Comment by doadin** [comment]
Do you also experience this with other addons off?
