### ISSUE TITLE
[Classic]v3.1.2 catsorttable error

### ISSUE THREAD

**Issue by Road-block** [doadin/Baggins#9]
`catsorttable` is defined as a local table in Baggins-Options.lua:289 but attempted to be used when constructing the menu for showUseButton in Baggins.lua:2162 where it is undefined / nil causing an error.

**Comment by Road-block** [comment]
Easiest fix is to move the table declaration in Baggins.lua instead.

**Comment by doadin** [comment]
yea its not even used in options? idk why its there. Fixed.
