### ISSUE TITLE
[WOTLK Classic] Ulduar Patch broke Baggins

### ISSUE THREAD

**Issue by Runkel79** [doadin/Baggins#92]
With the new Ulduar patch Blizzard changed a the Addon API for Classic (According to Wowhead the changes are the same that happened with Dragonflight arrived now in Classic Wrath.)

Here are the LUA Error:

the same that happened with the Dragonflight launch in retail and are now arriving in Classic Wrath.

Here's the LUA Error Bugsack displaying:

`192x Baggins/Baggins.lua:3120: attempt to call global 'GetContainerItemQuestInfo' (a nil value)
[string "@Baggins/Baggins.lua"]:3120: in function `UpdateItemButton'
[string "@Baggins/Baggins.lua"]:1919: in function `ReallyLayoutSection'
[string "@Baggins/Baggins.lua"]:760: in function `?'
[string "@Baggins/Baggins.lua"]:174: in function <Baggins/Baggins.lua:166>

Locals:
self = <table> {
 cannotDetachTooltip = true
 modules = <table> {
 }
 CancelTimer = <function> defined @Baggins/Libs/AceTimer-3.0/AceTimer-3.0.lua:147
 CreateItemButton = <function> defined @Baggins/Baggins.lua:2512
 GetIncludeRule = <function> defined @Baggins/Baggins-Filtering.lua:466
 RemoveSection = <function> defined @Baggins/Baggins.lua:3894
 GetCachedItem = <function> defined @Baggins/Baggins-Filtering.lua:538
 OptimizeSectionLayout = <function> defined @Baggins/Baggins.lua:1567
 UpdateSectionContents = <function> defined @Baggins/Baggins.lua:1198
 IsAnyBankOpen = <function> defined @Baggins/Baggins.lua:4170
 RemoveRule = <function> defined @Baggins/Baggins.lua:3911
 OnTextUpdate = <function> defined @Baggins/Baggins.lua:3634
 InitOptions = <function> defined @Baggins/Baggins-Options.lua:1081
 ScheduleTimer = <function> defined @Baggins/Libs/AceTimer-3.0/AceTimer-3.0.lua:94
 UpdateDB = <function> defined @Baggins/Baggins-Options.lua:1062
 GetBagTypes = <function> defined @Baggins/Baggins-Filtering.lua:89
 UpdateItemButtons = <function> defined @Baggins/Baggins.lua:2977
 LayoutSection = <function> defined @Baggins/Baggins.lua:1857
 OnBankOpened = <function> defined @Baggins/Baggins.lua:711
 SetEnabledState = <function> defined @Baggins/Libs/AceAddon-3.0/AceAddon-3.0.lua:420
 Hook = <function> defined @Baggins/Libs/AceHook-3.0/AceHook-3.0.lua:273
 RegisterSkin = <function> defined @Baggins/Baggins-Skins.lua:34
 InitBagCategoryOptions = <function> defined @Baggins/Baggins-Options.lua:3591
 UpdateLayout = <function> defined @Baggins/Baggins.lua:2966
 CountNormalSlots = <function> defined @Baggins/Baggins.lua:3722
 AddCustomRule = <function> defined @Baggins/Baggins-Filtering.lua:101
 RuleTypeIterator = <function> defined @Baggins/Baggins-Filtering.lua:123
 NewModule = <function> defined @Baggins/Libs/AceAddon-3.0/AceAddon-3.0.lua:231
 MoveBag = <function> defined @Baggins/Baggins.lua:3808
 ForceFullRefresh = <function> defined @Baggins/Baggins-Filtering.lua:434
 DoRecheckCompress = <function> defined @Baggins/Baggins-ItemOps.lua:230
 GetAce3Opts = <function> defined @Baggins/Baggins-Filtering.lua:152
 GetName = <function> defined @Baggins/Libs/AceAddon-3.0/AceAddon-3.0.lua:275
 MoveRule = <function> defined @Baggins/Baggins.lua:3843
 defaultcategories = <table> {
 }
 ClearSectionCaches = <function> defined @Baggins/Baggins.lua:997
 Disable = <function> defined @Baggins/Libs/AceAddon-3.0/AceAddon-3.0.lua:310
 CategoryMatchRemoved = <function> defined @Baggins/Baggins.lua:869
 Unhook = <function> defined @Baggins/Libs/AceHook-3.0/AceHook-3.0.lua:417
 CloseSpecialWindows = <function> defined @Baggins/Baggins.lua:4204
 CreateBagPlacementFrame = <function> defined @Baggins/Baggins.lua:1976
 IncludeItemInCategory = <function> defined @Baggins/Baggins-Filtering.lua:498
 Debug = <function> defined @Baggins/Baggins.lua:117
 CategoryMatchAdded = <function> defined @Baggins/Baggins.lua:809
 FireSignal = <function> defined @Baggins/Baggins.lua:197
 IsActive = <function> defined @Baggins/Baggins.lua:390
 CountAmmoSlots = <function> defined @Baggins/Baggins.lua:3726
 SlotMoved = <function> defined @Baggins/Baggins.lua:908
 SetDefaultModuleLibraries = <function> defined @Baggins/Libs/AceAddon-3.0/AceAddon-3.0.lua:363
 Baggins_CategoriesChanged = <function> defined `

**Comment by doadin** [comment]
I have just pushed an update hopefully this solves all issues, please let me know if you run into anything else.

**Comment by Runkel79** [comment]
Thank you

**Comment by Runkel79** [comment]
Closed this issue by accident, i'm sorry about that.

Baggins now loads correctly, no more LUA Errors but the majority of filters are not working so Baggins shows nothing and the Blizzard Bank frame opens (it shouldn't)

https://i.imgur.com/yYTrtv5.jpeg

**Comment by doadin** [comment]
I sent out another update not sure if its 100% working but making progress. The blizzard bank opening happens on retail too, I have yet to find a fix, but that is known as well, sorry.

**Comment by Runkel79** [comment]
Looking good so far i let you know if i notice any other bugs
