### ISSUE TITLE
Default Bank Showing

### ISSUE THREAD

**Issue by Spydawg** [doadin/Baggins#94]
Playing Wow RETAIL.

Using version 4.8.2 and previous versions too.     The default bank frames show when I open bank.   I have the option to disable bank frames on..

I have tried deleting the Baggins saved variables and reinstalled Baggins.

Also tried without any other addons loaded

Let me know if you need more info

**Comment by waytoomuchgaming** [comment]
I can confirm the bug is still here with v4.9.7-classic.

**Comment by Stidnoob** [comment]
This is still happening v5.0.0-classic

**Comment by doadin** [comment]
@waytoomuchgaming @Spydawg @FlinzyHC Sorry for the slow responce but this should now be fixed in v5.0.1( 78355439ff991644acad94078a142bde4b46f22e )
